export const texts = {
    // Informații aplicație
    app: {
      name: 'FoodOrder',
      tagline: 'Comandă mâncare delicioasă, livrată rapid',
      copyright: '© 2024 FoodOrder. Toate drepturile rezervate.',
    },
  
    // Navigare
    nav: {
      home: 'Acasă',
      catalog: 'Catalog',
      cart: 'Coș',
      profile: 'Profil',
      login: 'Autentificare',
      signup: 'Înregistrare',
      logout: 'Deconectare',
      coupons: 'Cupoane',
      streakCampaigns: 'Campanii',
    },
  
    // Pagina principală
    home: {
      /** Chip în hero tier: ×1.1 puncte per comandă */
      heroPointsMultiplierChip: '×{multiplier} puncte per comandă',
      /** Sub nodul „următor” pe timeline: x1.2 puncte */
      heroNextTierPointsLabel: 'x{multiplier} puncte',
      /** Ranguri viitoare neatinse — nod cu „?” în loc de icon */
      heroTierMysteryLabel: 'Mister',
      heroTitle: 'Mâncare delicioasă la ușa ta',
      categories: 'Categorii',
      recommended: 'Recomandate pentru tine',
      totalProductsInMenu: '{count} produse în meniu',
      viewAll: 'Vezi toate',
      /** Poartă inițială pe Home (logo + intrare); la refresh se arată din nou. */
      enterStore: 'Intră în magazin',
      order: 'Comandă acum !',
      heroOrderNowBadge: 'Comandă acum!',
      heroWelcomeBack: 'Bine ai revenit, {name}!',
      heroPointsLabel: '{count} puncte',
      heroPointsAvailable: 'disponibile de cheltuit',
      heroEarnPoints: 'Câștigă puncte cu fiecare comandă',
      heroEarnPointsDesc: 'Fiecare comandă îți aduce puncte de loialitate pe care le poți folosi pentru reduceri la comenzile viitoare.',
      heroMyRank: 'Rangul meu',
      heroMyPoints: 'Punctele mele',
      heroBenefits: 'Beneficii',
      heroHowItWorks: 'Cum funcționează',
      heroHowPointsWork: 'Comandă → Câștigă puncte → Folosește-le pentru reduceri',
      heroHowRanksWork: 'Comenzi → XP → rang mai mare → mai multe recompense',
      heroSignUpCta: 'Înregistrează-te pentru recompense',
      heroGuestFomoCta: 'Creează cont gratuit',
      heroGuestFomo: 'Clienți câștigă deja puncte bonus!',
      heroGuestFomoPercent : '73% deja castiga.',
      heroGuestFomoReward: 'Nu rata ofertele.',
      heroGuestFreeProductsHint:
        'Rangurile superioare deblochează produse gratuite. Înregistrează-te și comandă pentru a avansa.',
      welcomeTitle: 'Câștigă puncte la fiecare comandă',
      welcomeStepOrderTitle: 'Comandă și câștigă puncte',
      welcomeStepRanksTitle: 'Deblochează recompense pe rang',
      welcomeStepAdvanceTitle: 'Avansează în rang',
      welcomeRegisterNow: 'Creaza cont',
      /** Coloana primary pe Welcome (desktop): previzualizare produse */
      welcomeProductPeekTitle: 'Din meniu',
      welcomeProductPeekHint: 'Apasă pentru detalii',
      /** Bandă urgență / gamificare sub conținutul Welcome (timer decorativ) */
      welcomeUrgencyKicker: 'Timp limitat',
      welcomeUrgencyEndsIn: 'Se încheie în',
      welcomeUrgencyGamifyLines: [
        'Puncte bonus pentru comenzile plasate în această fereastră.',
        'Runda se apropie de final — nu amâna înregistrarea.',
        'Comandă acum și urcă mai rapid în rang.',
        'Zeci de clienți au activat deja bonusul de loialitate.',
        'Ultima șansă în această rundă de recompense.',
        'Fiecare minut contează pentru XP și beneficii.',
      ],
      heroXpProgress: '{current} / {target} XP',
      heroXpRemaining: 'mai ai {count} XP',
      heroMaxLevel: 'Nivel maxim atins!',
      heroNextRank: 'Următor:',
      heroUnlocks: 'Deblochează:',
      heroOrderForXp: 'Comandă acum!',
      heroFreeProductsSeeAbove: 'Recompensele tale gratuite active sunt afișate în cardul de mai sus.',
      heroNoFreeProducts: 'Campanii speciale cu produse gratuite pot apărea oricând.',
      heroFreeCampaignUrgencyKicker: 'Timp limitat',
      /** Banner urgență: „Oferta pentru {category} expiră în ” + timp (categorii separate prin virgulă dacă sunt mai multe). */
      heroFreeCampaignOfferExpiresWithCategory: 'Oferta pentru {category} expiră în ',
      /** Dacă nu putem determina categoria din campanii. */
      heroFreeCampaignOfferExpiresFallback: 'Oferta expiră în ',
      /** @deprecated folosit în alte layout-uri; păstrat pentru compatibilitate */
      heroFreeCampaignAfterTime:
        'Produsul gratis nu va dura la nesfârșit, câștigă-l acum!',
    },
  
    // Pagini autentificare
    auth: {
      loginTitle: 'Bine ai revenit!',
      loginSubtitle: 'Autentifică-te pentru a continua',
      signupTitle: 'Creează cont',
      signupSubtitle: 'Înregistrează-te pentru a plasa comenzi',
      emailLabel: 'Email',
      emailPlaceholder: 'exemplu@email.com',
      passwordLabel: 'Parolă',
      passwordPlaceholder: 'Introduceți parola',
      confirmPasswordLabel: 'Confirmă parola',
      confirmPasswordPlaceholder: 'Reintroduceți parola',
      nameLabel: 'Nume complet',
      namePlaceholder: 'Ion Popescu',
      phoneLabel: 'Telefon',
      phonePlaceholder: '+40 700 000 000',
      loginButton: 'Autentifică-te',
      signupButton: 'Creează cont',
      forgotPassword: 'Ai uitat parola?',
      forgotPasswordTitle: 'Resetează parola',
      forgotPasswordSubtitle: 'Introduceți emailul contului și vă vom trimite un link de resetare.',
      forgotPasswordButton: 'Trimite link de resetare',
      forgotPasswordSuccess: 'Dacă există un cont cu acest email, vei primi un link de resetare a parolei.',
      resetPasswordTitle: 'Parolă nouă',
      resetPasswordSubtitle: 'Introduceți noua parolă pentru contul dumneavoastră.',
      resetPasswordButton: 'Resetează parola',
      resetPasswordSuccess: 'Parola a fost resetată. Te poți autentifica acum cu noua parolă.',
      resetPasswordInvalidToken: 'Link-ul de resetare este invalid sau a expirat. Te rugăm să soliciți unul nou.',
      noAccount: 'Nu ai cont?',
      hasAccount: 'Ai deja cont?',
      orContinueWith: 'sau continuă cu',
    },
  
    // Pagina profil
    profile: {
      title: 'Profilul meu',
      editProfile: 'Editează profilul',
      saveChanges: 'Salvează',
      cancel: 'Anulează',
      orderHistory: 'Istoricul comenzilor',
      noOrders: 'Nu ai nicio comandă încă.',
      personalInfo: 'Informații personale',
      addressLabel: 'Adresă',
      addressPlaceholder: 'Stradă, număr, bloc, apartament',
      cityLabel: 'Oraș',
      cityPlaceholder: 'București',
      settings: 'Setările contului',
      deliveryAddresses: 'Adrese de livrare',
      noAddresses: 'Nicio adresă salvată',
      addAddress: 'Adaugă adresă',
      editAddress: 'Editează adresa',
      deleteAddress: 'Șterge adresa',
      setAsDefault: 'Setează ca implicită',
      defaultAddress: 'Adresă implicită',
      addressLabelField: 'Etichetă',
      addressLabelPlaceholder: 'ex.: Acasă, Birou',
      resetPassword: 'Resetează parola',
      resetPasswordDesc: 'Trimite un email pentru resetarea parolei',
      resetPasswordButton: 'Trimite email de resetare',
      resetPasswordSent: 'Emailul de resetare a fost trimis',
      deleteAccount: 'Șterge contul',
      deleteAccountDesc: 'Această acțiune este ireversibilă',
      deleteAccountButton: 'Șterge contul permanent',
      deleteAccountConfirmText: 'ȘTERGE CONTUL',
      deleteAccountWarning: 'Pentru a confirma ștergerea, introduceți parola și scrieți "ȘTERGE CONTUL"',
      accountDeleted: 'Contul a fost șters',
    },
  
    // Pagina catalog
    catalog: {
      title: 'Catalog',
      allCategories: 'Toate categoriile',
      filterBy: 'Filtrează după',
      sortBy: 'Sortează după',
      priceAsc: 'Preț: mic spre mare',
      priceDesc: 'Preț: mare spre mic',
      nameAsc: 'Nume A-Z',
      noProducts: 'Niciun produs găsit.',
      couponUrgencyMessage: 'Ai {count} {couponWord} active de folosit.',
      couponWordSingular: 'cupon',
      couponWordPlural: 'cupoane',
      couponUrgencyBadge: 'URGENT',
      addToCart: 'Adaugă în coș',
      added: 'Adăugat!',
    },
  
    // Pagina detalii produs
    productDetails: {
      ingredients: 'Ingrediente',
      allergens: 'Alergeni',
      reviews: 'Recenzii',
      noReviews: 'Nicio recenzie încă.',
      similarProducts: 'Produse similare',
      preparationTime: 'Timp de preparare',
      minutes: 'min',
      backToCatalog: 'Înapoi la catalog',
      addToCart: 'Adaugă în coș',
      outOfStock: 'Stoc epuizat',
    },
  
    // Pagina coș
    cart: {
      title: 'Coșul tău',
      empty: 'Coșul tău este gol',
      emptySubtitle: 'Adaugă produse pentru a continua',
      continueShopping: 'Continuă cumpărăturile',
      subtotal: 'Subtotal',
      delivery: 'Livrare',
      total: 'Total',
      checkout: 'Finalizează comanda',
      remove: 'Elimină',
      quantity: 'Cantitate',
      freeDelivery: 'Livrare gratuită',
      deliveryCost: 'Cost livrare',
    },
  
    // Pagina finalizare comandă
    checkout: {
      title: 'Finalizare comandă',
      deliveryInfo: 'Informații livrare',
      paymentMethod: 'Metodă de plată',
      cash: 'Numerar la livrare',
      card: 'Card credit / debit',
      orderSummary: 'Sumar comandă',
      placeOrder: 'Plasează comanda',
      processing: 'Se procesează...',
      orderSuccess: 'Comanda a fost plasată cu succes!',
      orderSuccessMessage: 'Vei primi un email de confirmare în scurt timp.',
      backToHome: 'Înapoi acasă',
      backToSavedAddresses: 'Alege o adresă salvată',
      activeCouponsTitle: 'Selecteaza cupoane',
      noEligibleCouponsForCart: 'Nu ai cupoane active aplicabile produselor din coșul curent.',
      couponForProduct: 'la {product}',
      pointsDisabledByCoupons: 'Punctele de loialitate nu pot fi folosite împreună cu cupoane aplicate pe comandă.',
    },

    coupons: {
      pageTitle: 'Cupoane',
      homeCardTitle: 'Activeaza cupoane',
      homeCardSubtitle: 'Activează cupoane din puncte și folosește reduceri la checkout.',
      homeCardAvailableCount: '{count} Cupoane',
      homeCardCta: 'Activează →',
      emptyCatalog: 'Nu există cupoane disponibile.',
      loginRequiredTitle: 'Autentificare necesară',
      loginRequiredDescription: 'Conectează-te pentru a activa cupoane.',
      activateSuccessTitle: 'Cupon activat',
      activateSuccessDescription: 'Cuponul a fost adăugat în portofel.',
      activateErrorDescription: 'Nu s-a putut activa cuponul.',
      defaultDescription: 'Reducere la produs țintă',
      costLabel: '-{points} puncte',
      missingPoints: 'Îți lipsesc {points} puncte',
      requiredTier: 'Necesită rangul {tier}',
      superiorTierFallback: 'superior',
      alreadyActive: 'Cupon deja activ în portofel',
      alreadyActivatedButton: 'Deja activat',
      activateButton: 'Activează',
    },

    myCoupons: {
      pageTitle: 'Cupoanele mele',
      empty: 'Nu ai cupoane activate încă.',
      statusLabel: 'Status:',
      statusActive: 'Activ',
      statusUsed: 'Folosit',
      statusExpired: 'Expirat',
      activatedAtLabel: 'Activat la:',
      usedAtLabel: 'Folosit la:',
      expiresAtLabel: 'Expiră la:',
      usedHint: 'Pentru o nouă comandă, activează din nou cuponul din pagina Cupoane.',
    },
  
    // Mesaje validare
    validation: {
      required: 'Acest câmp este obligatoriu',
      invalidEmail: 'Email invalid',
      passwordMin: 'Parola trebuie să aibă cel puțin 6 caractere',
      passwordMatch: 'Parolele nu coincid',
      invalidPhone: 'Număr de telefon invalid',
      invalidName: 'Numele trebuie să aibă cel puțin 2 caractere',
    },
  
    // Notificări
    notifications: {
      loginSuccess: 'Autentificat cu succes!',
      loginError: 'Email sau parolă incorectă',
      signupSuccess: 'Cont creat cu succes!',
      signupError: 'Eroare la crearea contului',
      logoutSuccess: 'Deconectat',
      profileUpdated: 'Profil actualizat',
      addedToCart: 'Produs adăugat în coș',
      removedFromCart: 'Produs eliminat din coș',
      orderPlaced: 'Comanda a fost plasată cu succes!',
      orderError: 'Eroare la plasarea comenzii',
      networkError: 'Eroare de rețea. Te rugăm să încerci din nou.',
      addressSaved: 'Adresa a fost salvată',
      addressDeleted: 'Adresa a fost ștearsă',
      passwordResetError: 'Eroare la trimiterea emailului',
      deleteAccountError: 'Eroare la ștergerea contului',
      invalidPassword: 'Parolă incorectă',
      invalidConfirmText: 'Textul de confirmare nu este corect',
    },
  
    // Comun
    common: {
      loading: 'Se încarcă...',
      error: 'A apărut o eroare',
      retry: 'Încearcă din nou',
      close: 'Închide',
      confirm: 'Confirmă',
      currency: 'RON',
      back: 'Înapoi',
    },
  
    // Bonus de bun venit la prima autentificare
    welcomeBonus: {
      title: 'Ai câștigat {count} puncte!',
      description: 'Le poți folosi la următoarea comandă pentru o reducere.',
      goToProducts: 'Mergi la produse',
    },
  
    // Analytics Admin
    analytics: {
      title: 'Analiză',
      subtitle: 'Rapoarte avansate despre afacerea ta',
      grossRevenue: 'Venit brut total',
      netProfitPerOrder: 'Profit net per comandă',
      aov: 'Valoare medie comandă (VMC)',
      salesByCategory: 'Volum vânzări pe categorie',
      revenueGrowthRate: 'Rata de creștere a veniturilor',
      totalDeliveryFees: 'Total taxe de livrare colectate',
      totalOrders: 'Total comenzi',
      vsPreviousPeriod: 'față de perioada anterioară',
      noData: 'Nu există date disponibile',
      topCustomers: 'Cei mai fideli clienți',
      frequentlyOrderedTogether: 'Comandate frecvent împreună',
      fulfillmentDeliveryVsInLocation: 'Livrare vs. La locație',
      fulfillmentTrend: 'Tendință fulfillment pe săptămână',
      delivery: 'Livrare',
      inLocation: 'La locație',
      revenue: 'Venit',
      orders: 'comenzi',
      cancellationRate: 'Rată de anulare',
      cancelledOrders: 'comenzi anulate',
      peakHours: 'Ore de vârf',
      dailyRevenueTrend: 'Tendință venit zilnic',
      pointsTitle: 'Analiză puncte de loialitate',
      pointsEarned: 'Puncte câștigate',
      pointsSpent: 'Puncte cheltuite',
      redemptionRate: 'Rată de utilizare puncte',
      redemptions: 'Utilizări',
      uniqueEarners: 'Utilizatori unici (câștigare)',
      uniqueRedeemers: 'Utilizatori unici (utilizare)',
      aovWithPoints: 'VMC cu puncte',
      aovWithoutPoints: 'VMC fără puncte',
      totalDiscountFromPoints: 'Total reduceri din puncte',
      topPointsEarners: 'Top câștigători de puncte',
      pointsTrend: 'Tendință zilnică puncte',
      balance: 'Sold',
      earned: 'Câștigate',
      spent: 'Cheltuite',
      streaksTitle: 'Analiză campanii streak',
      enrolled: 'Înscriși',
      completed: 'Finalizate',
      active: 'Active',
      avgStreak: 'Streak mediu',
      pointsAwarded: 'Puncte acordate',
      completionRate: 'Rată de finalizare',
      tiersTitle: 'Analiză ranguri',
      tierName: 'Nivel',
      userCount: 'Utilizatori',
      tierRevenue: 'Venit pe rang',
      tierAvgOrder: 'Comandă medie',
      tierMultiplier: 'Multiplicator',
      tierDistribution: 'Distribuție utilizatori pe rang',
      tierLtv: 'Valoare per rang',
    },
  
    // Plugin produse gratuite
    freeProducts: {
      adminTitle: 'Campanii produse gratuite pe rang',
      adminSubtitle:
        'Configurați campanii în care anumite produse devin gratuite pentru clienții dintr-un rang specific, într-o perioadă limitată.',
      adminMenuLabel: 'Produse gratuite pe rang',
      listTitle: 'Campanii',
      listDescription:
        'Fiecare campanie se aplică unui singur rang. Puteți crea mai multe campanii pentru ranguri sau perioade diferite.',
      listEmpty:
        'Nicio campanie. Creați una nouă pentru a oferi produse gratuite clienților fideli.',
      loading: 'Se încarcă...',
      createButton: 'Campanie nouă',
      editDialogTitle: 'Editează campania de produse gratuite',
      createDialogTitle: 'Campanie nouă de produse gratuite',
      dialogSubtitle:
        'Alegeți rangul țintă, perioada și produsele care vor fi gratuite pentru clienți.',
      nameLabel: 'Numele campaniei',
      namePlaceholder: 'ex.: Cafea gratuită pentru membrii Gold',
      tierLabel: 'Rang',
      tierPlaceholder: 'Alege rang',
      customTextLabel: 'Mesaj afișat clientului (opțional)',
      customTextPlaceholder: 'ex.: Produs gratuit pentru rangul tău de loialitate',
      startDateLabel: 'Data de început',
      endDateLabel: 'Data de sfârșit',
      minOrderValueLabel: 'Valoare minimă comandă (RON)',
      minOrderValueHelp: '0 = fără minim. Produsul gratuit se aplică doar peste acest prag.',
      productsLabel: 'Produse gratuite în campanie',
      productsHelp:
        'Bifați produsele care vor fi gratuite pentru utilizatorii din rangul selectat (max. 1 unitate per produs per comandă).',
      productsEmpty: 'Niciun produs în catalog.',
      productsCount: '{count} produse',
      activeBadge: 'Activ',
      cancel: 'Anulează',
      save: 'Salvează',
      deleteTitle: 'Șterge campania?',
      deleteDescription: 'Campania "{name}" va fi ștearsă permanent.',
      deleteConfirm: 'Șterge',
      toastLoadError: 'Nu s-au putut încărca campaniile sau datele auxiliare',
      toastSaveError: 'Eroare la salvare',
      toastDeleteError: 'Eroare la ștergere',
      toastCreated: 'Campanie creată',
      toastUpdated: 'Campanie actualizată',
      toastDeleted: 'Campanie ștearsă',
      validationNameRequired: 'Numele este obligatoriu',
      validationTierRequired: 'Te rugăm să selectezi un rang',
      validationDatesRequired: 'Data de început și de sfârșit sunt obligatorii',
      validationDatesOrder: 'Data de început trebuie să fie înainte de data de sfârșit',
      validationMinOrderValue:
        'Valoarea minimă a comenzii trebuie să fie un număr mai mare sau egal cu 0',
      warnNoProducts:
        'Campania nu are produse selectate. Poți continua, dar nu va avea efect până nu adaugi produse.',
      rankInfoNone:
        'Nu ai momentan produse gratuite pentru rangul tău, dar campanii speciale pot apărea oricând.',
      rankInfoActivePrefix: 'Ai produse gratuite active pentru rangul tău:',
      rankInfoMinOrder:
        'Comandă de {amount} RON și primești 1 {category}, GRATUIT.',
      rankInfoNoMinOrder:
        'Adaugă un produs din categoriile de mai jos în coș și îl primești gratuit (1 unitate).',
      rankInfoCta: 'Adaugă în coș pentru a beneficia.',
      availableOnlyForYourRank: 'Produse gratuite doar pentru rangul tău!',
      cartGridTitle: 'Produse gratuite pentru rangul tău',
      cartDiscountLabel: 'Produse gratuite',
      cartInfoNone:
        'Uneori poți primi produse gratuite pentru rangul tău de loialitate — urmărește ofertele speciale.',
    },
  
    // Streak V2 marketing
    streak: {
      pageTitle: 'Campanii Streak',
      pageSubtitle: 'Completează provocările și câștigă puncte bonus',
      noCampaigns: 'Nicio campanie activă în acest moment.',
      homeCardTitle: 'Câștigă puncte BONUS',
      homeCardActive: 'Streak activ — menține streak-ul!',
      homeCardAvailable: 'Provocări disponibile — înscrie-te acum!',
      homeCardLost: 'Ai pierdut un streak — vezi detalii!',
      homeCardCompleted: 'Streak finalizat — felicitări!',
      homeCardCta: 'Vezi provocările',
      homeCardPoints: '+{points} puncte posibile',
      comboCardTitle: 'Combouri speciale',
      comboCardSubtitle: 'În curând...',
      homeGamifiedDealUnit: 'puncte bonus',
      homeGamifiedUrgencyDays: '{days} zile rămase',
      homeGamifiedUrgencyTwo: 'Ultimele 2 zile',
      homeGamifiedUrgencyLast: 'Ultima zi — nu rata bonusul',
      homeGamifiedTrustAvailable: 'Exclusiv pentru provocări — bonus mai mare decât o comandă obișnuită.',
      homeGamifiedHeadlineAvailable: 'Castiga cupoane',
      homeGamifiedHeadlineActive: 'Castiga cupoane',
      homeGamifiedSubActive: 'Mai ai nevoie de comenzi — nu întrerupe streak-ul.',
      homeGamifiedHeadlineLost: 'Poți începe o nouă provocare',
      homeGamifiedHeadlineCompleted: 'Ai deblocat bonusul',
      homeGamifiedSubCompleted: 'Felicitări — punctele sunt ale tale.',
      homeGamifiedCtaAvailable: 'Înscrie-te și câștigă',
      homeGamifiedCtaActive: 'Continuă provocarea',
      homeGamifiedCtaLost: 'Vezi provocările',
      homeGamifiedCtaCompleted: 'Descoperă alte oferte',
      preview: {
        earnPrefix: 'Castiga',
        pointsSuffix: 'puncte',
        savingsLabel: 'Castigi până la {amount} RON',
        ordersLabel: 'Comenzi',
        thresholdOrderLabel: 'comandă',
        statusLive: 'Live',
        statusUrgent: 'Urgent',
        statusLastChance: 'Last chance',
        statusFailed: 'Lost',
        statusCompleted: 'Completed',
        ctaJoin: 'Join',
        ctaActive: 'Active',
        ctaCompleted: 'Done',
        ctaDetails: 'Activeaza',
        ctaView: 'Vezi',
        ctaUnlock: 'Deblocheaza',
        lostOverlay: 'Pierdut',
        lossShort: 'Do not lose your progress!',
        daysLeft: '{days} days!',
        leave: 'Leave',
      },
      detail: {
        title: 'Campaign details',
        subtitle: 'Full rules, rewards, progress, and actions',
      },
    },
  
    // Texte admin comune
    admin: {
      error: 'Eroare',
      success: 'Succes',
      save: 'Salvează',
      saving: 'Se salvează...',
      cancel: 'Anulează',
      delete: 'Șterge',
      deleting: 'Se șterge...',
      edit: 'Editează',
      add: 'Adaugă',
      create: 'Creează',
      search: 'Caută...',
      noData: 'Nu există date de afișat',
      rowsPerPage: 'Rânduri pe pagină:',
      processing: 'Se procesează...',
      loading: 'Se încarcă...',
      view: 'Vezi',
      disconnect: 'Deconectează',
      export: 'Exportă CSV',
      loginTitle: 'Food Admin',
      loginSubtitle: 'Autentifică-te pentru a accesa panoul de administrare',
      loginEmailLabel: 'Email',
      loginPasswordLabel: 'Parolă',
      loginButton: 'Autentifică-te',
      loginAuthenticating: 'Se autentifică...',
      loginSuccess: 'Autentificare reușită',
      loginFailed: 'Autentificare eșuată',
      loginDevCredentials: 'Credențiale implicite: admin@foodorder.com / admin123secure',
      controlPanel: 'Panou de control',
      sidebarMain: 'Principal',
      sidebarSystem: 'Sistem',
      sidebarLogout: 'Deconectare',
      navDashboard: 'Tablou de bord',
      navAnalytics: 'Analiză',
      navProducts: 'Produse',
      navCategories: 'Categorii',
      navProductOptions: 'Opțiuni produse',
      navOrders: 'Comenzi',
      navUsers: 'Utilizatori',
      navWelcomeBonus: 'Bonus de bun venit',
      navFreeProducts: 'Produse gratuite pe rang',
      navAddonRules: 'Reguli suplimente',
      navSettings: 'Setări',
      headerToggleLight: 'Comută la modul luminos',
      headerToggleDark: 'Comută la modul întunecat',
      dashboardTitle: 'Tablou de bord',
      dashboardSubtitle: 'Bun venit! Iată o prezentare generală a afacerii tale.',
      ordersToday: 'Comenzi azi',
      ordersPlacedToday: 'comenzi plasate azi',
      revenueToday: 'Venit azi',
      totalEarnings: 'câștiguri totale',
      newUsers: 'Utilizatori noi',
      registrationsToday: 'înregistrări azi',
      revenueThisMonth: 'Venit luna aceasta',
      salesLast7Days: 'Vânzări ultimele 7 zile',
      ordersByStatus: 'Comenzi pe status',
      recentOrders: 'Comenzi recente',
      last10Orders: 'Ultimele 10 comenzi plasate',
      viewAll: 'Vezi toate',
      noRecentOrders: 'Nicio comandă recentă',
      couldNotLoadData: 'Nu s-au putut încărca datele',
      couldNotLoadDashboard: 'Nu s-au putut încărca datele tabloului de bord',
      product: 'produs',
      products: 'produse',
      revenue: 'Venit',
      client: 'Client',
      statusPending: 'În așteptare',
      statusConfirmed: 'Confirmată',
      statusPreparing: 'În preparare',
      statusDelivering: 'În livrare',
      statusDelivered: 'Livrată',
      statusCancelled: 'Anulată',
      ordersTitle: 'Comenzi',
      ordersSubtitle: 'Vizualizează și gestionează comenzile',
      orderId: 'ID Comandă',
      date: 'Dată',
      type: 'Tip',
      inLocation: 'La locație',
      delivery: 'Livrare',
      addressLocation: 'Adresă / Locație',
      total: 'Total',
      payment: 'Plată',
      status: 'Status',
      card: 'Card',
      cash: 'Numerar',
      newOrderAlert: 'Comandă nouă!',
      newOrdersCount: '{count} {orderWord} noi în așteptare',
      newOrderSingular: 'comandă',
      newOrderPlural: 'comenzi',
      viewOrders: 'Vezi comenzile',
      allOrders: 'Toate comenzile',
      filterByStatus: 'Filtrează după status',
      fulfillmentType: 'Tip fulfillment',
      all: 'Toate',
      selected: 'selectate',
      changeStatus: 'Schimbă statusul:',
      bulkUpdate: 'Actualizare în masă',
      updated: 'actualizate',
      errors: 'erori',
      searchOrderPlaceholder: 'Caută după ID sau adresă...',
      noOrders: 'Nicio comandă',
      orderDetails: 'Detalii comandă',
      placedOn: 'Plasată pe',
      clientInfo: 'Informații client',
      tel: 'Tel:',
      deliveryAddress: 'Adresă de livrare',
      inLocationLabel: 'La locație',
      inLocationDesc: 'Comanda se ridică la locație. Livrați comanda la masa indicată de client.',
      tableLabel: 'Masa la care se livrează:',
      tableNotSet: '— (clientul nu a specificat masa)',
      tablePrefix: 'Masa',
      tableCorrection: 'Numărul corect al mesei:',
      tableOptional: '(opțional, dacă clientul a greșit)',
      tableUpdated: 'Numărul mesei actualizat',
      couldNotUpdateTable: 'Nu s-a putut actualiza numărul mesei',
      productsLabel: 'Produse',
      subtotal: 'Subtotal',
      deliveryLabel: 'Livrare',
      freeProducts: 'Produse gratuite',
      currentStatus: 'Status curent:',
      paymentMethod: 'Metodă de plată:',
      statusUpdated: 'Status actualizat la "{status}"',
      statusUpdateError: 'Eroare la actualizarea statusului',
      productsTitle: 'Produse',
      productsSubtitle: 'Gestionează produsele din meniu',
      addProduct: 'Adaugă produs',
      category: 'Categorie',
      allCategories: 'Toate categoriile',
      image: 'Imagine',
      name: 'Nume',
      price: 'Preț',
      rating: 'Rating',
      available: 'Disponibil',
      unavailable: 'Indisponibil',
      recommended: 'Recomandat',
      yes: 'Da',
      no: 'Nu',
      editProduct: 'Editează produsul',
      addNewProduct: 'Adaugă produs nou',
      productFormSubtitle: 'Completați detaliile produsului',
      productImage: 'Imaginea produsului',
      imageUploadHint: 'Click pentru a încărca o imagine.\nMax 5MB, format JPG, PNG sau WebP',
      imageTooLarge: 'Imaginea trebuie să fie mai mică de 5MB',
      nameRequired: 'Numele este obligatoriu',
      priceRequired: 'Prețul trebuie să fie un număr valid',
      categoryRequired: 'Selectați o categorie',
      priceLabel: 'Preț ({currency}) *',
      categoryLabel: 'Categorie *',
      prepTimeLabel: 'Timp de preparare (minute)',
      ingredientsLabel: 'Ingrediente',
      ingredientsPlaceholder: 'Făină, mozzarella, roșii, busuioc...',
      ingredientsSeparator: 'Separați ingredientele cu virgulă',
      allergensLabel: 'Alergeni (opțional)',
      allergensPlaceholder: 'Gluten, lactate, ouă...',
      allergensSeparator: 'Separați alergenii cu virgulă (ex.: gluten, lactate)',
      availableForOrders: 'Disponibil pentru comenzi',
      recommendedLabel: 'Recomandat (apare în "Recomandate pentru tine")',
      recommendedDesc: 'Produsele marcate apar pe pagina principală în secțiunea Recomandate',
      displayOrder: 'Ordine de afișare (opțional)',
      displayOrderDesc: 'Număr mai mic = afișat primul. Lasă gol = ultimul.',
      addonToCart: 'Supliment coș',
      addonActiveDesc: 'Apare în secțiunea "Adaugă la comandă" pe pagina Coș',
      addonDisabledDesc: 'Plugin-ul suplimente este dezactivat în Setări → Plugin-uri',
      productUpdated: 'Produs actualizat cu succes',
      productCreated: 'Produs creat cu succes',
      productSaveError: 'Eroare la salvarea produsului',
      confirmDeleteProduct: 'Confirmă ștergerea',
      confirmDeleteProductDesc: 'Ești sigur că vrei să ștergi produsul "{name}"? Această acțiune nu poate fi anulată.',
      productDeleted: 'Produs șters cu succes',
      productDeleteError: 'Eroare la ștergerea produsului',
      searchProducts: 'Caută produse...',
      noProducts: 'Niciun produs',
      descriptionLabel: 'Descriere',
      descriptionPlaceholder: 'Descrierea produsului...',
      selectPlaceholder: 'Selectează...',
      categoriesTitle: 'Categorii',
      categoriesSubtitle: 'Gestionează categoriile de produse',
      addCategory: 'Adaugă categorie',
      noCategoriesEmpty: 'Nicio categorie. Adaugă prima categorie pentru a începe.',
      editCategory: 'Editează categoria',
      addNewCategory: 'Adaugă categorie nouă',
      categoryFormSubtitle: 'Completați detaliile categoriei',
      slugLabel: 'Identificator (slug) *',
      slugDesc: 'Folosit intern pentru identificare (fără spații, doar litere mici)',
      slugError: 'Identificatorul poate conține doar litere mici, cifre și underscore',
      displayNameLabel: 'Nume afișat *',
      displayNameRequired: 'Numele afișat este obligatoriu',
      identifierRequired: 'Identificatorul este obligatoriu',
      descriptionCatLabel: 'Descriere',
      descriptionCatPlaceholder: 'Descrierea categoriei...',
      categoryIcon: 'Iconița categoriei',
      selectIconHint: 'Selectați o icooniță pentru această categorie',
      categoryUpdated: 'Categorie actualizată cu succes',
      categoryCreated: 'Categorie creată cu succes',
      categorySaveError: 'Eroare la salvarea categoriei',
      confirmDeleteCategory: 'Confirmă ștergerea',
      confirmDeleteCategoryDesc: 'Ești sigur că vrei să ștergi categoria "{name}"?',
      categoryWarningProducts: 'Atenție: Această categorie conține {count} produse!',
      categoryDeleted: 'Categorie ștearsă cu succes',
      categoryDeleteError: 'Eroare la ștergerea categoriei',
      usersTitle: 'Utilizatori',
      usersSubtitle: 'Gestionează utilizatorii și permisiunile',
      user: 'Utilizator',
      orders: 'Comenzi',
      role: 'Rol',
      registered: 'Înregistrat',
      admin: 'Administrator',
      moderator: 'Moderator',
      userRole: 'Utilizator',
      blocked: 'Blocat',
      active: 'Activ',
      makeAdmin: 'Fă administrator',
      makeModerator: 'Fă moderator',
      makeUser: 'Fă utilizator',
      block: 'Blochează',
      unblock: 'Deblochează',
      blockUser: 'Blochează utilizatorul',
      unblockUser: 'Deblochează utilizatorul',
      blockConfirmDesc: 'Ești sigur că vrei să blochezi utilizatorul "{name}"? Nu va mai putea accesa contul.',
      unblockConfirmDesc: 'Ești sigur că vrei să deblochezi utilizatorul "{name}"?',
      userBlocked: 'Utilizator blocat cu succes',
      userUnblocked: 'Utilizator deblocat cu succes',
      userBlockError: 'Eroare la blocarea utilizatorului',
      roleUpdated: 'Rol actualizat la "{role}"',
      roleUpdateError: 'Eroare la actualizarea rolului',
      userDetails: 'Detalii utilizator',
      totalOrders: 'Total comenzi',
      searchUsersPlaceholder: 'Caută după nume sau email...',
      noUsers: 'Niciun utilizator',
      csvHeaders: {
        id: 'ID',
        name: 'Nume',
        role: 'Rol',
        status: 'Status',
        orders: 'Comenzi',
        points: 'Puncte',
        registered: 'Înregistrat',
      },
      settingsTitle: 'Setări',
      settingsSubtitle: 'Configurează opțiunile aplicației',
      saveChanges: 'Salvează modificările',
      settingsSaved: 'Setări salvate',
      settingsSavedDesc: 'Modificările au fost aplicate cu succes.',
      settingsLoadError: 'Nu s-au putut încărca setările.',
      settingsSaveError: 'Nu s-au putut salva setările.',
      deliveryAndOrders: 'Livrare și comenzi la locație',
      deliveryAndOrdersDesc: 'Configurați taxele, condițiile de livrare și opțiunile pentru comenzile la locație',
      deliveryFeeLabel: 'Taxă de livrare ({currency})',
      minOrderLabel: 'Comandă minimă ({currency})',
      freeDeliveryLabel: 'Livrare gratuită de la ({currency})',
      hasTables: 'Locația are mese',
      hasTablesDesc: 'Dacă este activat, câmpul pentru numărul mesei apare în admin pentru comenzile la locație. Dezactivați pentru brutării sau magazine fără mese.',
      operatingHours: 'Program de funcționare',
      operatingHoursDesc: 'Setați orele de deschidere și închidere',
      openingTime: 'Ora de deschidere',
      closingTime: 'Ora de închidere',
      contactInfo: 'Informații de contact',
      contactInfoDesc: 'Datele de contact afișate în aplicație',
      contactEmail: 'Email contact',
      contactPhone: 'Telefon contact',
      pointsPerOrder: 'Puncte per comandă livrată',
      pointsPerOrderDesc: 'Regula magazinului: câte puncte se acordă pentru fiecare comandă marcată ca "livrată" (valoare fixă, înainte de multiplicatorii de rang).',
      pointsPerOrderLabel: 'Puncte per comandă',
      pointsPerOrderHint: 'Exemplu: 5 sau 7. Fără sistemul de puncte activat în Plugin-uri, această valoare nu are efect.',
      plugins: 'Plugin-uri',
      pluginsDesc: 'Activează sau dezactivează module suplimentare',
      pluginLoyaltyPoints: 'Puncte de loialitate',
      pluginLoyaltyPointsDesc: 'Permite utilizatorilor să câștige și să folosească puncte pentru reduceri la finalizarea comenzii',
      pluginStreakCampaigns: 'Campanii streak',
      pluginStreakDesc: 'Campanii de tip streak (zile consecutive, zile pe săptămână, zile lucrătoare) cu puncte bonus',
      pluginWelcomeBonus: 'Puncte bonus de bun venit',
      pluginWelcomeBonusDesc: 'Popup și alocare la înregistrare. Numărul de puncte se setează pe pagina "Bonus de bun venit" din meniu.',
      pluginAddons: 'Suplimente coș',
      pluginAddonsDesc: 'Secțiunea "Adaugă la comandă" în coș – sosuri, băuturi, desert, garnituri',
      pluginTiers: 'Plugin ranguri',
      pluginTiersDesc: 'Sistem de avansare bazat pe XP cu multiplicator de puncte per rang. Setările detaliate sunt pe pagina Ranguri.',
      pluginFreeProducts: 'Produse gratuite pe rang',
      pluginFreeProductsDesc: 'Permite definirea de campanii cu produse gratuite pentru ranguri specifice într-o perioadă limitată.',
      welcomeBonusTitle: 'Bonus de bun venit',
      welcomeBonusSubtitle: 'Câte puncte primește un utilizator nou la înregistrare (popup + credit în cont).',
      giftPoints: 'Puncte cadou',
      giftPointsDesc: 'Valoarea este folosită doar dacă atât plugin-ul Puncte de Loialitate cât și plugin-ul Bonus de Bun Venit sunt activate în Setări. 0 = fără puncte și fără popup.',
      pointsCount: 'Număr de puncte',
      pointsExample: 'Exemplu: 5, 10 sau 25.',
      welcomeBonusSaved: 'Punctele de bun venit au fost actualizate.',
      welcomeBonusLoadError: 'Nu s-au putut încărca setările.',
      welcomeBonusSaveError: 'Nu s-a putut salva.',
      analyticsErrorMsg: 'Acest grafic sau tabel nu a putut fi afișat. Încearcă să reîncarci pagina sau să schimbi tab-ul.',
      analyticsLoadError: 'Nu s-au putut încărca datele de analiză',
      productOptionsTitle: 'Opțiuni produse',
      productOptionsSubtitle: 'Definește șabloane de opțiuni per categorie și aplică-le produselor',
      categorySelect: 'Categorie:',
      chooseCategory: 'Alege o categorie',
      newTemplate: 'Șablon nou',
      noTemplates: 'Niciun șablon de opțiuni pentru {category}',
      noTemplatesHint: 'Creați un șablon pentru a defini opțiuni comune (ex.: Mărime, Topping extra)',
      createTemplate: 'Creează șablon',
      templateNameRequired: 'Numele șablonului este obligatoriu',
      groupNameRequired: 'Fiecare grup trebuie să aibă un nume',
      groupNeedsOption: 'Grupul "{name}" necesită cel puțin o opțiune',
      templateUpdated: 'Șablon actualizat',
      templateCreated: 'Șablon creat',
      templateSaveError: 'Eroare la salvare',
      templateDeleted: 'Șablon șters (produsele păstrează opțiunile lor locale)',
      templateDeleteError: 'Eroare la ștergere',
      templateApplied: 'Șablon aplicat la {count} produs(e)',
      templateApplyError: 'Eroare la aplicare',
      templateSynced: 'Sincronizat',
      templateSyncResult: '{count} produs(e) actualizat(e)',
      templateSyncError: 'Eroare la sincronizare',
      groups: 'grup(uri)',
      synced: 'sincronizat',
      recurrenceConsecutive: 'Zile consecutive (Streak clasic)',
      recurrenceRolling: 'Fereastră glisantă',
      rewardSingle: 'Prag unic (Totul sau Nimic)',
      rewardSteps: 'Praguri incrementale (Scară)',
      rewardMultiplier: 'Multiplicator streak',
      imageSaved: 'Imagine salvată',
      imagesSaveError: 'Nu s-a putut salva imaginea',
      couldNotLoadEnrollments: 'Nu s-au putut încărca înscrierile',
      datesRequired: 'Datele de început și de sfârșit sunt obligatorii',
      daysMinimum: 'Numărul de zile trebuie să fie >= 1',
      datesOrder: 'Data de început trebuie să fie înainte de data de sfârșit',
      couldNotLoadThresholds: 'Nu s-au putut încărca pragurile de puncte',
      invalidThresholdData: 'Date invalide',
      invalidThresholdDesc: 'Punctele și reducerea trebuie să fie numere pozitive.',
      thresholdDeleted: 'Prag șters',
      couldNotDeleteThreshold: 'Nu s-a putut șterge',
      tiersLoadError: 'Nu s-au putut încărca setările de rang.',
      tiersSaved: 'Setări salvate',
      tiersSavedDesc: 'Setările de rang au fost actualizate.',
      tiersSaveError: 'Nu s-au putut salva setările.',
      tiersListLoadError: 'Nu s-au putut încărca rangurile de loialitate.',
      confirmDeleteTier: 'Ești sigur că vrei să ștergi acest rang?',
      tierDeleted: 'Rang șters',
      tierDeleteError: 'Nu s-a putut șterge rangul.',
      tierSaveError: 'Nu s-au putut salva modificările.',
      editTier: 'Editează rangul',
      addNewTier: 'Adaugă rang nou',
      addonFreeDelivery: 'Livrare gratuită',
      addonLowPrice: 'Preț redus',
      addonAddedToCart: 'Adăugat în coș',
      errorOccurred: 'A apărut o eroare',
      errorFallbackMessage: 'Ceva nu a funcționat. Poți încerca să reîncarci pagina.',
      reloadPage: 'Reîncarcă pagina',
      ordersCsvHeaders: ['ID', 'Dată', 'Client', 'Email', 'Telefon', 'Adresă', 'Oraș', 'Tip', 'Subtotal', 'Livrare', 'Total', 'Plată', 'Status'],
    },

    adminCoupons: {
      pageTitle: 'Admin cupoane',
      createCardTitle: 'Creează cupon',
      titleLabel: 'Titlu',
      targetProductLabel: 'Produs țintă',
      targetProductPlaceholder: 'Alege produsul',
      discountLabel: 'Reducere %',
      pointsCostLabel: 'Cost puncte',
      requiredTierLabel: 'Rang minim necesar',
      requiredTierPlaceholder: 'Alege rang minim',
      noTierRequired: 'Fără rang minim',
      imageLabel: 'Imagine cupon',
      imageUploading: 'Se încarcă imaginea...',
      imageUploaded: 'Imagine încărcată',
      imageUploadErrorTitle: 'Eroare upload',
      imageUploadError: 'Nu s-a putut încărca imaginea',
      imagePreviewAlt: 'Previzualizare cupon',
      descriptionLabel: 'Descriere',
      activeLabel: 'Activ',
      analyticsTitle: 'Analitice cupoane',
      totalDiscountLabel: 'Reducere totală acordată',
      totalActivatedLabel: 'Activate',
      totalUsedLabel: 'Folosite',
      usageRateLabel: 'Rata utilizare',
      listTitle: 'Lista cupoane',
      deactivate: 'Dezactivează',
      activate: 'Activează',
      created: 'Cupon creat',
      createError: 'Nu s-a putut crea cuponul',
      loadError: 'Nu s-au putut încărca cupoanele',
      missingProductTitle: 'Produs lipsă',
      missingProductDescription: 'Selectează produsul țintă pentru cupon.',
      pointsLabel: 'puncte',
      targetShort: 'target',
    },
  
    // Mesaje validare extinse
    validationExtended: {
      passwordMinChars: 'Parola trebuie să aibă cel puțin 8 caractere',
      passwordUppercase: 'Parola trebuie să conțină cel puțin o literă mare',
      passwordLowercase: 'Parola trebuie să conțină cel puțin o literă mică',
      passwordDigit: 'Parola trebuie să conțină cel puțin o cifră',
      confirmPassword: 'Confirmă parola',
      passwordsNoMatch: 'Parolele nu coincid',
      addressMin: 'Adresa trebuie să aibă cel puțin 5 caractere',
      cityMin: 'Orașul trebuie să aibă cel puțin 2 caractere',
      labelRequired: 'Eticheta este obligatorie',
      acceptTerms: 'Trebuie să accepți Termenii și Condițiile',
    },
  
    // Succes finalizare comandă
    checkoutSuccess: {
      orderPlaced: 'Comandă plasată!',
      orderStatus: 'Status comandă',
      stepReceived: 'Comandă primită',
      stepConfirmed: 'Confirmată',
      stepPreparing: 'În preparare',
      stepDelivering: 'În livrare',
      stepDelivered: 'Livrată',
      estimatedTime: 'Timp estimat:',
      orderedProducts: 'Produse comandate',
      subtotal: 'Subtotal',
      delivery: 'Livrare',
      free: 'Gratuit',
      pointsDiscount: 'Reducere din puncte',
      freeProducts: 'Produse gratuite',
      total: 'Total',
      savedAmount: 'Ai economisit {amount} {currency} la această comandă!',
      pointsEarned: '+{points} puncte câștigate!',
      totalBalance: 'Sold total:',
      points: 'puncte',
      currentLevel: 'Nivel curent',
      xpRemaining: 'mai ai {xp} XP până la {tier}',
      deliveryDetails: 'Detalii livrare',
      tableService: 'Servire la masă',
      tablePrefixed: 'Masa {number}',
      cashPayment: 'Plată cu numerar',
      cardPayment: 'Plată cu cardul',
      orderAgain: 'Comandă din nou',
      orderAgainPoints: 'Comandă din nou — câștigă mai multe puncte!',
      viewAllOrders: 'Vezi toate comenzile',
      myOrders: 'Comenzile mele',
      confirmingPayment: 'Se confirmă plata...',
      paymentConfirmError: 'Eroare la confirmarea plății',
      paymentFailed: 'Confirmarea plății a eșuat',
      backToCheckout: 'Înapoi la finalizare comandă',
      redirecting: 'Redirecționare către autentificare...',
      requestNewLink: 'Solicită link nou',
      backToLogin: 'Înapoi la autentificare',
    },
  
    // Catalog extins
    catalogExtended: {
      productFound: '{count} produs găsit',
      productsFound: '{count} produse găsite',
      inCategory: ' în categoria "{category}"',
      forSearch: ' pentru "{query}"',
    },
  
    // Texte progres coș
    cartProgress: {
      freeDelivery: 'Livrare gratuită',
      addMoreFreeDelivery: 'Adaugă {amount} {currency} — livrare gratuită',
      freeDeliveryUnlocked: 'Livrare GRATUITĂ deblocată!',
      addMoreFreeDeliveryGamified: 'Adaugă {amount} {currency} pentru livrare GRATUITĂ!',
      freeProductUnlocked: '{product} gratuit deblocat',
      addMoreFreeProduct: 'Adaugă {amount} {currency} — {product} gratuit',
      freeProductsUnlockedGamified: 'Produse GRATUITE deblocate: {products}!',
      addMoreFreeProductGamified: 'Adaugă {amount} {currency} și primești {product} GRATUIT!',
      freeProductUnlockedAddFromCatalog: 'Ai deblocat {product}! Adaugă-l din catalog.',
      checkoutSavings: 'Finalizează — economisești {amount} {currency}',
      product: 'Produs',
    },
  
    // Texte afișare rang
    tierDisplay: {
      beginner: 'Începător',
      pointsMultiplierBenefit: 'Primești x{mult} puncte la fiecare comandă livrată',
      orderForXp: 'Comandă pentru a câștiga XP și a avansa',
      nextTierPoints: 'x{mult} puncte la fiecare comandă',
      xpPerRon: '+1 XP pentru fiecare {amount} {currency} cheltuiți',
      xpPerOrder: 'XP se acumulează cu fiecare comandă',
    },
  
    // Nume categorii
    categoryNames: {
      pizza: 'Pizza',
      burger: 'Burgeri',
      paste: 'Paste',
      salate: 'Salate',
      desert: 'Deserturi',
      bauturi: 'Băuturi',
    },
  
    // Footer
    footer: {
      termsAndConditions: 'Termeni și Condiții',
      phone: '0800 123 456',
      email: 'contact@foodorder.com',
      location: 'București, România',
      hours: [
        'Lun - Vin: 10:00 - 23:00',
        'Sâmbătă: 11:00 - 00:00',
        'Duminică: 11:00 - 22:00',
      ],
    },
  
    // Texte card campanie streak
    streakCard: {
      consecutiveDays: 'Zile consecutive',
      rollingWindow: 'Fereastră glisantă',
      streakBroken: 'Streak întrerupt',
      notEnoughDays: 'Nu mai sunt suficiente zile',
      canLeaveAndJoin: 'Poți părăsi această campanie și te poți înscrie în alta.',
      rewardThresholds: 'Praguri de recompensă',
      earnBonusPoints: 'Câștigă puncte BONUS',
      activeCampaigns: 'Campanii active',
      completeStreakExclusive: 'Completează streak-ul și deblochează recompense exclusive',
      completeStreakBonus: 'Completează streak-ul și câștigă puncte bonus',
    },
  
    // Configurator produs / modal
    modal: {
      processing: 'Se procesează...',
    },
  } as const;
  
  export type TextsType = typeof texts;