// /**
//  * Text labels and messages for the application
//  * Centralized for easy localization and consistency
//  */

// export const texts = {
//   // App info
//   app: {
//     name: 'FoodOrder',
//     tagline: 'Comandă mâncare delicioasă, livrată rapid',
//     copyright: '© 2024 FoodOrder. Toate drepturile rezervate.',
//   },

//   // Navigation
//   nav: {
//     home: 'Acasă',
//     catalog: 'Catalog',
//     cart: 'Coș',
//     profile: 'Profil',
//     login: 'Autentificare',
//     signup: 'Înregistrare',
//     logout: 'Deconectare',
//   },

//   // Home page
//   home: {
//     heroTitle: 'Mâncare Delicioasă la Ușa Ta',
//     heroSubtitle: 'Descoperă cele mai bune preparate din zona ta',
//     searchPlaceholder: 'Caută preparate sau restaurante...',
//     categories: 'Categorii',
//     recommended: 'Recomandate pentru tine',
//     totalProductsInMenu: '{count} produse în meniu',
//     viewAll: 'Vezi toate',
//     orderNow: 'Comandă acum',
//   },

//   // Auth pages
//   auth: {
//     loginTitle: 'Bine ai revenit!',
//     loginSubtitle: 'Conectează-te pentru a continua',
//     signupTitle: 'Creează cont',
//     signupSubtitle: 'Înregistrează-te pentru a comanda',
//     emailLabel: 'Email',
//     emailPlaceholder: 'exemplu@email.com',
//     passwordLabel: 'Parolă',
//     passwordPlaceholder: 'Introdu parola',
//     confirmPasswordLabel: 'Confirmă parola',
//     confirmPasswordPlaceholder: 'Reintrodu parola',
//     nameLabel: 'Nume complet',
//     namePlaceholder: 'Ion Popescu',
//     phoneLabel: 'Telefon',
//     phonePlaceholder: '0700 000 000',
//     loginButton: 'Conectează-te',
//     signupButton: 'Creează cont',
//     forgotPassword: 'Ai uitat parola?',
//     forgotPasswordTitle: 'Resetează parola',
//     forgotPasswordSubtitle: 'Introdu email-ul contului și îți vom trimite un link pentru resetare.',
//     forgotPasswordButton: 'Trimite link de resetare',
//     forgotPasswordSuccess: 'Dacă există un cont cu acest email, vei primi un link pentru resetarea parolei.',
//     resetPasswordTitle: 'Parolă nouă',
//     resetPasswordSubtitle: 'Introdu noua parolă pentru contul tău.',
//     resetPasswordButton: 'Resetează parola',
//     resetPasswordSuccess: 'Parola a fost resetată. Poți să te autentifici cu noua parolă.',
//     resetPasswordInvalidToken: 'Link-ul de resetare este invalid sau a expirat. Solicită unul nou.',
//     noAccount: 'Nu ai cont?',
//     hasAccount: 'Ai deja cont?',
//     orContinueWith: 'sau continuă cu',
//   },

//   // Profile page
//   profile: {
//     title: 'Profilul meu',
//     editProfile: 'Editează profil',
//     saveChanges: 'Salvează',
//     cancel: 'Anulează',
//     orderHistory: 'Istoric comenzi',
//     noOrders: 'Nu ai nicio comandă încă.',
//     personalInfo: 'Informații personale',
//     addressLabel: 'Adresă',
//     addressPlaceholder: 'Strada, număr, bloc, apartament',
//     cityLabel: 'Oraș',
//     cityPlaceholder: 'București',
//     // New settings section
//     settings: 'Setări cont',
//     deliveryAddresses: 'Adrese de livrare',
//     noAddresses: 'Nu ai adrese salvate',
//     addAddress: 'Adaugă adresă',
//     editAddress: 'Editează adresa',
//     deleteAddress: 'Șterge adresa',
//     setAsDefault: 'Setează ca principală',
//     defaultAddress: 'Adresă principală',
//     addressLabelField: 'Denumire',
//     addressLabelPlaceholder: 'ex: Acasă, Birou',
//     // Account actions
//     resetPassword: 'Resetare parolă',
//     resetPasswordDesc: 'Trimite un email pentru a reseta parola',
//     resetPasswordButton: 'Trimite email de resetare',
//     resetPasswordSent: 'Email-ul de resetare a fost trimis',
//     deleteAccount: 'Șterge cont',
//     deleteAccountDesc: 'Această acțiune este ireversibilă',
//     deleteAccountButton: 'Șterge contul definitiv',
//     deleteAccountConfirmText: 'ȘTERGE CONTUL',
//     deleteAccountWarning: 'Pentru a confirma ștergerea, introdu parola și scrie "ȘTERGE CONTUL"',
//     accountDeleted: 'Contul a fost șters',
//   },

//   // Catalog page
//   catalog: {
//     title: 'Catalog',
//     allCategories: 'Toate categoriile',
//     filterBy: 'Filtrează după',
//     sortBy: 'Sortează după',
//     priceAsc: 'Preț crescător',
//     priceDesc: 'Preț descrescător',
//     nameAsc: 'Nume A-Z',
//     noProducts: 'Nu s-au găsit produse.',
//     addToCart: 'Adaugă în coș',
//     added: 'Adăugat!',
//   },

//   // Product details page
//   productDetails: {
//     ingredients: 'Ingrediente',
//     allergens: 'Alergeni',
//     reviews: 'Recenzii',
//     noReviews: 'Nu există recenzii încă.',
//     similarProducts: 'Produse similare',
//     preparationTime: 'Timp preparare',
//     minutes: 'min',
//     backToCatalog: 'Înapoi la catalog',
//     addToCart: 'Adaugă în coș',
//     outOfStock: 'Indisponibil',
//   },

//   // Cart page
//   cart: {
//     title: 'Coșul tău',
//     empty: 'Coșul tău este gol',
//     emptySubtitle: 'Adaugă produse pentru a continua',
//     continueShopping: 'Continuă cumpărăturile',
//     subtotal: 'Subtotal',
//     delivery: 'Livrare',
//     total: 'Total',
//     checkout: 'Finalizează comanda',
//     remove: 'Elimină',
//     quantity: 'Cantitate',
//     freeDelivery: 'Livrare gratuită',
//     deliveryCost: 'Cost livrare',
//   },

//   // Checkout page
//   checkout: {
//     title: 'Finalizare comandă',
//     deliveryInfo: 'Informații livrare',
//     paymentMethod: 'Metodă plată',
//     cash: 'Numerar la livrare',
//     card: 'Card bancar',
//     orderSummary: 'Sumar comandă',
//     placeOrder: 'Plasează comanda',
//     processing: 'Se procesează...',
//     orderSuccess: 'Comandă plasată cu succes!',
//     orderSuccessMessage: 'Vei primi un email de confirmare în curând.',
//     backToHome: 'Înapoi acasă',
//     backToSavedAddresses: 'Alege o adresă salvată',
//   },

//   // Validation messages
//   validation: {
//     required: 'Acest câmp este obligatoriu',
//     invalidEmail: 'Email invalid',
//     passwordMin: 'Parola trebuie să aibă minim 6 caractere',
//     passwordMatch: 'Parolele nu coincid',
//     invalidPhone: 'Număr de telefon invalid',
//     invalidName: 'Numele trebuie să aibă minim 2 caractere',
//   },

//   // Notifications
//   notifications: {
//     loginSuccess: 'Te-ai conectat cu succes!',
//     loginError: 'Email sau parolă incorectă',
//     signupSuccess: 'Cont creat cu succes!',
//     signupError: 'Eroare la crearea contului',
//     logoutSuccess: 'Te-ai deconectat',
//     profileUpdated: 'Profil actualizat',
//     addedToCart: 'Produs adăugat în coș',
//     removedFromCart: 'Produs eliminat din coș',
//     orderPlaced: 'Comandă plasată cu succes!',
//     orderError: 'Eroare la plasarea comenzii',
//     networkError: 'Eroare de rețea. Încearcă din nou.',
//     addressSaved: 'Adresa a fost salvată',
//     addressDeleted: 'Adresa a fost ștearsă',
//     passwordResetError: 'Eroare la trimiterea email-ului',
//     deleteAccountError: 'Eroare la ștergerea contului',
//     invalidPassword: 'Parolă incorectă',
//     invalidConfirmText: 'Textul de confirmare nu este corect',
//   },

//   // Common
//   common: {
//     loading: 'Se încarcă...',
//     error: 'A apărut o eroare',
//     retry: 'Încearcă din nou',
//     close: 'Închide',
//     confirm: 'Confirmă',
//     currency: 'RON',
//     back: 'Înapoi',
//   },

//   // Cadou puncte la prima autentificare
//   welcomeBonus: {
//     title: 'Ai câștigat {count} puncte!',
//     description: 'Le poți folosi la următoarea comandă pentru reducere.',
//     goToProducts: 'Mergi la produse',
//   },

//   // Admin Analytics
//   analytics: {
//     title: 'Analitice',
//     subtitle: 'Rapoarte avansate despre afacerea ta',
//     grossRevenue: 'Venit Brut Total',
//     netProfitPerOrder: 'Profit Net per Comandă',
//     aov: 'Valoarea Medie a Coșului (AOV)',
//     salesByCategory: 'Volumul Vânzărilor per Categorie',
//     revenueGrowthRate: 'Rata de Creștere a Veniturilor',
//     totalDeliveryFees: 'Total Taxe de Livrare Colectate',
//     totalOrders: 'Total Comenzi',
//     vsPreviousPeriod: 'vs. perioada anterioară',
//     noData: 'Nu există date',
//     topCustomers: 'Top clienți fideli',
//     frequentlyOrderedTogether: 'Frecvent comandate împreună',
//     fulfillmentDeliveryVsInLocation: 'Livrare vs. În locație',
//     fulfillmentTrend: 'Trend fulfillment pe săptămâni',
//     delivery: 'Livrare',
//     inLocation: 'În locație',
//     revenue: 'Venituri',
//     orders: 'comenzi',
//     cancellationRate: 'Rată Anulări',
//     cancelledOrders: 'comenzi anulate',
//     peakHours: 'Ore de Vârf',
//     dailyRevenueTrend: 'Trend Venituri Zilnice',
//     // Points
//     pointsTitle: 'Analitice Puncte Loialitate',
//     pointsEarned: 'Puncte Câștigate',
//     pointsSpent: 'Puncte Consumate',
//     redemptionRate: 'Rată Utilizare Puncte',
//     redemptions: 'Răscumpărări',
//     uniqueEarners: 'Utilizatori unici (câștig)',
//     uniqueRedeemers: 'Utilizatori unici (consum)',
//     aovWithPoints: 'AOV cu puncte',
//     aovWithoutPoints: 'AOV fără puncte',
//     totalDiscountFromPoints: 'Total Reduceri din Puncte',
//     topPointsEarners: 'Top câștigători puncte',
//     pointsTrend: 'Trend puncte zilnic',
//     balance: 'Sold',
//     earned: 'Câștigate',
//     spent: 'Consumate',
//     // Streaks
//     streaksTitle: 'Analitice Campanii Streak',
//     enrolled: 'Înscriși',
//     completed: 'Completate',
//     active: 'Activi',
//     avgStreak: 'Media streak',
//     pointsAwarded: 'Puncte acordate',
//     completionRate: 'Rată completare',
//     // Tiers
//     tiersTitle: 'Analitice Ranguri (Tiers)',
//     tierName: 'Nivel',
//     userCount: 'Utilizatori',
//     tierRevenue: 'Venituri nivel',
//     tierAvgOrder: 'Medie comandă',
//     tierMultiplier: 'Multiplicator',
//     tierDistribution: 'Distribuție utilizatori per nivel',
//     tierLtv: 'Valoare per nivel',
//   },

//   // Free products plugin (produse gratis pe rank)
//   freeProducts: {
//     adminTitle: 'Campanii produse gratis pe rank',
//     adminSubtitle:
//       'Configurează campanii în care anumite produse devin gratuite pentru clienții cu un anumit nivel (tier), într-o perioadă limitată.',
//     adminMenuLabel: 'Produse gratis pe rank',
//     listTitle: 'Campanii',
//     listDescription:
//       'Fiecare campanie se aplică unui singur nivel (tier). Poți crea mai multe campanii pentru niveluri diferite sau perioade diferite.',
//     listEmpty:
//       'Nicio campanie. Creează una nouă pentru a oferi produse gratis clienților fideli.',
//     loading: 'Se încarcă...',
//     createButton: 'Campanie nouă',
//     editDialogTitle: 'Editează campania de produse gratis',
//     createDialogTitle: 'Campanie nouă de produse gratis',
//     dialogSubtitle:
//       'Alege nivelul țintă, perioada și produsele care vor fi gratuite pentru clienți.',
//     nameLabel: 'Nume campanie',
//     namePlaceholder: 'ex: Gratis cafea pentru Gold',
//     tierLabel: 'Nivel (tier)',
//     tierPlaceholder: 'Alege nivelul',
//     customTextLabel: 'Mesaj afișat clientului (opțional)',
//     customTextPlaceholder: 'ex: Produs gratuit pentru nivelul tău de loialitate',
//     startDateLabel: 'Data start',
//     endDateLabel: 'Data sfârșit',
//     minOrderValueLabel: 'Valoare minimă comandă (RON)',
//     minOrderValueHelp: '0 = fără prag de sumă. Gratuitatea se aplică doar peste acest prag.',
//     productsLabel: 'Produse gratuite în campanie',
//     productsHelp:
//       'Bifează produsele care vor fi gratuite pentru utilizatorii cu nivelul selectat (maxim 1 bucată per produs per comandă).',
//     productsEmpty: 'Nu există produse în catalog.',
//     productsCount: '{count} produse',
//     activeBadge: 'Activă',
//     cancel: 'Anulare',
//     save: 'Salvează',
//     deleteTitle: 'Șterge campania?',
//     deleteDescription: 'Campania „{name}” va fi ștearsă permanent.',
//     deleteConfirm: 'Șterge',
//     toastLoadError: 'Nu s-au putut încărca campaniile sau datele auxiliare',
//     toastSaveError: 'Eroare la salvare',
//     toastDeleteError: 'Eroare la ștergere',
//     toastCreated: 'Campanie creată',
//     toastUpdated: 'Campanie actualizată',
//     toastDeleted: 'Campanie ștearsă',
//     validationNameRequired: 'Numele este obligatoriu',
//     validationTierRequired: 'Selectează un nivel (tier)',
//     validationDatesRequired: 'Datele de start și sfârșit sunt obligatorii',
//     validationDatesOrder: 'Data de start trebuie să fie înainte de data de sfârșit',
//     validationMinOrderValue:
//       'Valoarea minimă a comenzii trebuie să fie un număr mai mare sau egal cu 0',
//     warnNoProducts:
//       'Campania nu are niciun produs selectat. Poți continua, dar nu va avea efect până nu adaugi produse.',
//     // Frontend user-facing
//     rankInfoNone:
//       'Momentan nu ai produse gratuite pentru acest nivel, dar pot apărea campanii speciale pentru tine în orice moment.',
//     rankInfoActivePrefix: 'Ai produse gratuite active pentru nivelul tău:',
//     rankInfoMinOrder:
//       'Comandă minim {amount} RON în coș și primești 1 buc. gratuit din fiecare produs de mai jos.',
//     rankInfoNoMinOrder:
//       'Adaugă în coș un produs din lista de mai jos și îl primești gratuit (1 buc.).',
//     rankInfoCta: 'Adaugă în coș pentru a beneficia.',
//     cartGridTitle: 'Produse gratuite pentru nivelul tău',
//     cartDiscountLabel: 'Produse gratuite',
//     cartInfoNone:
//       'Uneori poți primi produse gratuite pentru nivelul tău de loialitate — urmărește ofertele speciale.',
//   },

//   // Streak V2 marketing
//   streak: {
//     pageTitle: 'Campanii Streak',
//     pageSubtitle: 'Completează provocări și câștigă puncte bonus',
//     noCampaigns: 'Momentan nu există campanii active.',
//     homeCardTitle: 'Câștigă puncte BONUS',
//     homeCardActive: 'Streak activ — continuă seria!',
//     homeCardAvailable: 'Provocări disponibile — înscrie-te acum!',
//     homeCardLost: 'Ai pierdut un streak — vezi detalii!',
//     homeCardCompleted: 'Streak completat — felicitări! 🎉',
//     homeCardCta: 'Vezi provocările',
//     homeCardPoints: '+{points} puncte posibile',
//     comboCardTitle: 'Combouri speciale',
//     comboCardSubtitle: 'În curând...',

//     /** Home card — doar varianta gamified (deal + urgență + CTA) */
//     homeGamifiedDealUnit: 'puncte bonus',
//     homeGamifiedUrgencyDays: 'Mai ai {days} zile',
//     homeGamifiedUrgencyTwo: 'Ultimele 2 zile',
//     homeGamifiedUrgencyLast: 'Ultima zi — nu pierde bonusul',
//     homeGamifiedTrustAvailable: 'Exclusiv din provocări — bonus mai mare decât la o simplă comandă.',
//     homeGamifiedHeadlineAvailable: 'Cea mai bună ofertă de puncte',
//     homeGamifiedHeadlineActive: 'Bonus mare la finalul provocării',
//     homeGamifiedSubActive: 'Mai ai nevoie de comenzi — nu întrerupe seria.',
//     homeGamifiedHeadlineLost: 'Poți începe din nou o provocare',
//     homeGamifiedHeadlineCompleted: 'Ai deblocat bonusul',
//     homeGamifiedSubCompleted: 'Felicitări — punctele sunt ale tale.',
//     homeGamifiedCtaAvailable: 'Înscrie-te și câștigă',
//     homeGamifiedCtaActive: 'Continuă provocarea',
//     homeGamifiedCtaLost: 'Vezi provocările',
//     homeGamifiedCtaCompleted: 'Descoperă alte oferte',
//   },
// } as const;

// export type TextsType = typeof texts;


/**
 * Text labels and messages for the application
 * Centralized for easy localization and consistency
 */

// export const texts = {
//   // App info
//   app: {
//     name: 'FoodOrder',
//     tagline: 'Order delicious food, delivered fast',
//     copyright: '© 2024 FoodOrder. All rights reserved.',
//   },

//   // Navigation
//   nav: {
//     home: 'Home',
//     catalog: 'Catalog',
//     cart: 'Cart',
//     profile: 'Profile',
//     login: 'Login',
//     signup: 'Sign Up',
//     logout: 'Logout',
//   },

//   // Home page
//   home: {
//     heroTitle: 'Delicious Food at Your Door',
//     categories: 'Categories',
//     recommended: 'Recommended for you',
//     totalProductsInMenu: '{count} products in menu',
//     viewAll: 'View all',
//     orderNow: 'Order now',
//     // Hero hub (combined hero + tier)
//     heroOrderNowBadge: 'Order now!',
//     heroWelcomeBack: 'Welcome back, {name}!',
//     heroPointsLabel: '{count} points',
//     heroPointsAvailable: 'available to spend',
//     heroEarnPoints: 'Earn points with every order',
//     heroEarnPointsDesc: 'Each order earns you loyalty points you can spend for discounts on future orders.',
//     heroMyRank: 'My Rank',
//     heroMyPoints: 'My Points',
//     heroBenefits: 'Benefits',
//     heroHowItWorks: 'How it works',
//     heroHowPointsWork: 'Order → Earn points → Spend on discounts',
//     heroHowRanksWork: 'Orders → XP → higher rank → more rewards',
//     heroSignUpCta: 'Sign up for rewards',
//     heroGuestFomo: 'Other customers are already earning bonus points!',
//     heroGuestFomoReward: "Don't miss the rewards.",
//     /** Guest hero — visible promise about free products (not hidden in collapsed UI) */
//     heroGuestFreeProductsHint:
//       'Higher ranks can unlock free product rewards. Sign up and order to climb the ladder.',
//     heroXpProgress: '{current} / {target} XP',
//     heroXpRemaining: '{count} XP to go',
//     heroMaxLevel: 'Max level reached!',
//     heroNextRank: 'Next:',
//     heroUnlocks: 'Unlocks:',
//     heroOrderForXp: 'Order now for XP',
//     /** When free products card is shown above the accordion */
//     heroFreeProductsSeeAbove: 'Your active free rewards are listed in the card above.',
//     heroNoFreeProducts: 'Special free product campaigns may appear at any time.',
//     /** Free campaign countdown (above Benefits / How it works accordion) */
//     heroFreeCampaignUrgencyKicker: 'Limited time',
//     heroFreeCampaignAfterTime: 'This free product will not last forever — claim it now!',
//   },

//   // Auth pages
//   auth: {
//     loginTitle: 'Welcome back!',
//     loginSubtitle: 'Sign in to continue',
//     signupTitle: 'Create account',
//     signupSubtitle: 'Register to place orders',
//     emailLabel: 'Email',
//     emailPlaceholder: 'example@email.com',
//     passwordLabel: 'Password',
//     passwordPlaceholder: 'Enter your password',
//     confirmPasswordLabel: 'Confirm password',
//     confirmPasswordPlaceholder: 'Re-enter your password',
//     nameLabel: 'Full name',
//     namePlaceholder: 'John Doe',
//     phoneLabel: 'Phone',
//     phonePlaceholder: '+1 000 000 0000',
//     loginButton: 'Sign in',
//     signupButton: 'Create account',
//     forgotPassword: 'Forgot your password?',
//     forgotPasswordTitle: 'Reset password',
//     forgotPasswordSubtitle: 'Enter your account email and we will send you a reset link.',
//     forgotPasswordButton: 'Send reset link',
//     forgotPasswordSuccess: 'If an account exists with this email, you will receive a password reset link.',
//     resetPasswordTitle: 'New password',
//     resetPasswordSubtitle: 'Enter the new password for your account.',
//     resetPasswordButton: 'Reset password',
//     resetPasswordSuccess: 'Password has been reset. You can now sign in with your new password.',
//     resetPasswordInvalidToken: 'The reset link is invalid or has expired. Please request a new one.',
//     noAccount: "Don't have an account?",
//     hasAccount: 'Already have an account?',
//     orContinueWith: 'or continue with',
//   },

//   // Profile page
//   profile: {
//     title: 'My Profile',
//     editProfile: 'Edit profile',
//     saveChanges: 'Save',
//     cancel: 'Cancel',
//     orderHistory: 'Order history',
//     noOrders: 'You have no orders yet.',
//     personalInfo: 'Personal information',
//     addressLabel: 'Address',
//     addressPlaceholder: 'Street, number, building, apartment',
//     cityLabel: 'City',
//     cityPlaceholder: 'New York',
//     // New settings section
//     settings: 'Account settings',
//     deliveryAddresses: 'Delivery addresses',
//     noAddresses: 'No saved addresses',
//     addAddress: 'Add address',
//     editAddress: 'Edit address',
//     deleteAddress: 'Delete address',
//     setAsDefault: 'Set as default',
//     defaultAddress: 'Default address',
//     addressLabelField: 'Label',
//     addressLabelPlaceholder: 'e.g.: Home, Office',
//     // Account actions
//     resetPassword: 'Reset password',
//     resetPasswordDesc: 'Send an email to reset your password',
//     resetPasswordButton: 'Send reset email',
//     resetPasswordSent: 'Reset email has been sent',
//     deleteAccount: 'Delete account',
//     deleteAccountDesc: 'This action is irreversible',
//     deleteAccountButton: 'Permanently delete account',
//     deleteAccountConfirmText: 'DELETE ACCOUNT',
//     deleteAccountWarning: 'To confirm deletion, enter your password and type "DELETE ACCOUNT"',
//     accountDeleted: 'Account has been deleted',
//   },

//   // Catalog page
//   catalog: {
//     title: 'Catalog',
//     allCategories: 'All categories',
//     filterBy: 'Filter by',
//     sortBy: 'Sort by',
//     priceAsc: 'Price: low to high',
//     priceDesc: 'Price: high to low',
//     nameAsc: 'Name A-Z',
//     noProducts: 'No products found.',
//     addToCart: 'Add to cart',
//     added: 'Added!',
//   },

//   // Product details page
//   productDetails: {
//     ingredients: 'Ingredients',
//     allergens: 'Allergens',
//     reviews: 'Reviews',
//     noReviews: 'No reviews yet.',
//     similarProducts: 'Similar products',
//     preparationTime: 'Preparation time',
//     minutes: 'min',
//     backToCatalog: 'Back to catalog',
//     addToCart: 'Add to cart',
//     outOfStock: 'Out of stock',
//   },

//   // Cart page
//   cart: {
//     title: 'Your cart',
//     empty: 'Your cart is empty',
//     emptySubtitle: 'Add products to continue',
//     continueShopping: 'Continue shopping',
//     subtotal: 'Subtotal',
//     delivery: 'Delivery',
//     total: 'Total',
//     checkout: 'Checkout',
//     remove: 'Remove',
//     quantity: 'Quantity',
//     freeDelivery: 'Free delivery',
//     deliveryCost: 'Delivery cost',
//   },

//   // Checkout page
//   checkout: {
//     title: 'Checkout',
//     deliveryInfo: 'Delivery information',
//     paymentMethod: 'Payment method',
//     cash: 'Cash on delivery',
//     card: 'Credit / debit card',
//     orderSummary: 'Order summary',
//     placeOrder: 'Place order',
//     processing: 'Processing...',
//     orderSuccess: 'Order placed successfully!',
//     orderSuccessMessage: 'You will receive a confirmation email shortly.',
//     backToHome: 'Back to home',
//     backToSavedAddresses: 'Choose a saved address',
//   },

//   // Validation messages
//   validation: {
//     required: 'This field is required',
//     invalidEmail: 'Invalid email',
//     passwordMin: 'Password must be at least 6 characters',
//     passwordMatch: 'Passwords do not match',
//     invalidPhone: 'Invalid phone number',
//     invalidName: 'Name must be at least 2 characters',
//   },

//   // Notifications
//   notifications: {
//     loginSuccess: 'Signed in successfully!',
//     loginError: 'Incorrect email or password',
//     signupSuccess: 'Account created successfully!',
//     signupError: 'Error creating account',
//     logoutSuccess: 'Signed out',
//     profileUpdated: 'Profile updated',
//     addedToCart: 'Product added to cart',
//     removedFromCart: 'Product removed from cart',
//     orderPlaced: 'Order placed successfully!',
//     orderError: 'Error placing order',
//     networkError: 'Network error. Please try again.',
//     addressSaved: 'Address has been saved',
//     addressDeleted: 'Address has been deleted',
//     passwordResetError: 'Error sending email',
//     deleteAccountError: 'Error deleting account',
//     invalidPassword: 'Incorrect password',
//     invalidConfirmText: 'Confirmation text is not correct',
//   },

//   // Common
//   common: {
//     loading: 'Loading...',
//     error: 'An error occurred',
//     retry: 'Try again',
//     close: 'Close',
//     confirm: 'Confirm',
//     currency: 'USD',
//     back: 'Back',
//   },

//   // Welcome bonus points on first login
//   welcomeBonus: {
//     title: 'You earned {count} points!',
//     description: 'You can use them on your next order for a discount.',
//     goToProducts: 'Go to products',
//   },

//   // Admin Analytics
//   analytics: {
//     title: 'Analytics',
//     subtitle: 'Advanced reports about your business',
//     grossRevenue: 'Total Gross Revenue',
//     netProfitPerOrder: 'Net Profit per Order',
//     aov: 'Average Order Value (AOV)',
//     salesByCategory: 'Sales Volume by Category',
//     revenueGrowthRate: 'Revenue Growth Rate',
//     totalDeliveryFees: 'Total Delivery Fees Collected',
//     totalOrders: 'Total Orders',
//     vsPreviousPeriod: 'vs. previous period',
//     noData: 'No data available',
//     topCustomers: 'Top loyal customers',
//     frequentlyOrderedTogether: 'Frequently ordered together',
//     fulfillmentDeliveryVsInLocation: 'Delivery vs. In-location',
//     fulfillmentTrend: 'Fulfillment trend by week',
//     delivery: 'Delivery',
//     inLocation: 'In-location',
//     revenue: 'Revenue',
//     orders: 'orders',
//     cancellationRate: 'Cancellation Rate',
//     cancelledOrders: 'cancelled orders',
//     peakHours: 'Peak Hours',
//     dailyRevenueTrend: 'Daily Revenue Trend',
//     // Points
//     pointsTitle: 'Loyalty Points Analytics',
//     pointsEarned: 'Points Earned',
//     pointsSpent: 'Points Spent',
//     redemptionRate: 'Points Redemption Rate',
//     redemptions: 'Redemptions',
//     uniqueEarners: 'Unique users (earning)',
//     uniqueRedeemers: 'Unique users (redeeming)',
//     aovWithPoints: 'AOV with points',
//     aovWithoutPoints: 'AOV without points',
//     totalDiscountFromPoints: 'Total Discounts from Points',
//     topPointsEarners: 'Top points earners',
//     pointsTrend: 'Daily points trend',
//     balance: 'Balance',
//     earned: 'Earned',
//     spent: 'Spent',
//     // Streaks
//     streaksTitle: 'Streak Campaign Analytics',
//     enrolled: 'Enrolled',
//     completed: 'Completed',
//     active: 'Active',
//     avgStreak: 'Average streak',
//     pointsAwarded: 'Points awarded',
//     completionRate: 'Completion rate',
//     // Tiers
//     tiersTitle: 'Tier Analytics',
//     tierName: 'Level',
//     userCount: 'Users',
//     tierRevenue: 'Tier revenue',
//     tierAvgOrder: 'Average order',
//     tierMultiplier: 'Multiplier',
//     tierDistribution: 'User distribution by tier',
//     tierLtv: 'Value per tier',
//   },

//   // Free products plugin 
//   freeProducts: {
//     adminTitle: 'Free product campaigns by tier',
//     adminSubtitle:
//       'Configure campaigns where certain products become free for customers at a specific tier, within a limited time period.',
//     adminMenuLabel: 'Free products by tier',
//     listTitle: 'Campaigns',
//     listDescription:
//       'Each campaign applies to a single tier. You can create multiple campaigns for different tiers or time periods.',
//     listEmpty:
//       'No campaigns. Create a new one to offer free products to loyal customers.',
//     loading: 'Loading...',
//     createButton: 'New campaign',
//     editDialogTitle: 'Edit free products campaign',
//     createDialogTitle: 'New free products campaign',
//     dialogSubtitle:
//       'Choose the target tier, time period, and the products that will be free for customers.',
//     nameLabel: 'Campaign name',
//     namePlaceholder: 'e.g.: Free coffee for Gold members',
//     tierLabel: 'Tier',
//     tierPlaceholder: 'Choose tier',
//     customTextLabel: 'Message shown to customer (optional)',
//     customTextPlaceholder: 'e.g.: Free product for your loyalty tier',
//     startDateLabel: 'Start date',
//     endDateLabel: 'End date',
//     minOrderValueLabel: 'Minimum order value (USD)',
//     minOrderValueHelp: '0 = no minimum. The free item only applies above this threshold.',
//     productsLabel: 'Free products in campaign',
//     productsHelp:
//       'Check the products that will be free for users at the selected tier (max 1 unit per product per order).',
//     productsEmpty: 'No products in catalog.',
//     productsCount: '{count} products',
//     activeBadge: 'Active',
//     cancel: 'Cancel',
//     save: 'Save',
//     deleteTitle: 'Delete campaign?',
//     deleteDescription: 'The campaign "{name}" will be permanently deleted.',
//     deleteConfirm: 'Delete',
//     toastLoadError: 'Could not load campaigns or auxiliary data',
//     toastSaveError: 'Error saving',
//     toastDeleteError: 'Error deleting',
//     toastCreated: 'Campaign created',
//     toastUpdated: 'Campaign updated',
//     toastDeleted: 'Campaign deleted',
//     validationNameRequired: 'Name is required',
//     validationTierRequired: 'Please select a tier',
//     validationDatesRequired: 'Start and end dates are required',
//     validationDatesOrder: 'Start date must be before end date',
//     validationMinOrderValue:
//       'Minimum order value must be a number greater than or equal to 0',
//     warnNoProducts:
//       'The campaign has no products selected. You can continue, but it will have no effect until you add products.',
//     // Frontend user-facing
//     rankInfoNone:
//       'You currently have no free products for your tier, but special campaigns may appear for you at any time.',
//     rankInfoActivePrefix: 'You have active free products for your tier:',
//     rankInfoMinOrder:
//       'Order at least {amount} USD in your cart and get 1 unit of each product from the categories below for free.',
//     rankInfoNoMinOrder:
//       'Add a product from the categories below to your cart and get it for free (1 unit).',
//     rankInfoCta: 'Add to cart to take advantage.',
//     availableOnlyForYourRank: 'Free products available only for your rank!',
//     cartGridTitle: 'Free products for your tier',
//     cartDiscountLabel: 'Free products',
//     cartInfoNone:
//       'Sometimes you can receive free products for your loyalty tier — keep an eye out for special offers.',
//   },

//   // Streak V2 marketing
//   streak: {
//     pageTitle: 'Streak Campaigns',
//     pageSubtitle: 'Complete challenges and earn bonus points',
//     noCampaigns: 'No active campaigns at the moment.',
//     homeCardTitle: 'Earn BONUS points',
//     homeCardActive: 'Streak active — keep the streak going!',
//     homeCardAvailable: 'Challenges available — sign up now!',
//     homeCardLost: 'You lost a streak — see details!',
//     homeCardCompleted: 'Streak completed — congratulations! 🎉',
//     homeCardCta: 'View challenges',
//     homeCardPoints: '+{points} possible points',
//     comboCardTitle: 'Special combos',
//     comboCardSubtitle: 'Coming soon...',

//     /** Home card — gamified variant only (deal + urgency + CTA) */
//     homeGamifiedDealUnit: 'bonus points',
//     homeGamifiedUrgencyDays: '{days} days left',
//     homeGamifiedUrgencyTwo: 'Last 2 days',
//     homeGamifiedUrgencyLast: 'Last day — don\'t miss the bonus',
//     homeGamifiedTrustAvailable: 'Exclusive to challenges — bigger bonus than a regular order.',
//     homeGamifiedHeadlineAvailable: 'Best points offer',
//     homeGamifiedHeadlineActive: 'Big bonus at the end of the challenge',
//     homeGamifiedSubActive: 'You still need more orders — don\'t break the streak.',
//     homeGamifiedHeadlineLost: 'You can start a new challenge',
//     homeGamifiedHeadlineCompleted: 'You unlocked the bonus',
//     homeGamifiedSubCompleted: 'Congratulations — the points are yours.',
//     homeGamifiedCtaAvailable: 'Sign up and earn',
//     homeGamifiedCtaActive: 'Continue the challenge',
//     homeGamifiedCtaLost: 'View challenges',
//     homeGamifiedCtaCompleted: 'Discover other offers',
//   },

//   // Admin common texts
//   admin: {
//     // Common
//     error: 'Error',
//     success: 'Success',
//     save: 'Save',
//     saving: 'Saving...',
//     cancel: 'Cancel',
//     delete: 'Delete',
//     deleting: 'Deleting...',
//     edit: 'Edit',
//     add: 'Add',
//     create: 'Create',
//     search: 'Search...',
//     noData: 'No data to display',
//     rowsPerPage: 'Rows per page:',
//     processing: 'Processing...',
//     loading: 'Loading...',
//     view: 'View',
//     disconnect: 'Disconnect',
//     export: 'Export CSV',

//     // Login
//     loginTitle: 'Food Admin',
//     loginSubtitle: 'Sign in to access the admin panel',
//     loginEmailLabel: 'Email',
//     loginPasswordLabel: 'Password',
//     loginButton: 'Sign in',
//     loginAuthenticating: 'Authenticating...',
//     loginSuccess: 'Authentication successful',
//     loginFailed: 'Authentication failed',
//     loginDevCredentials: 'Default credentials: admin@foodorder.com / admin123secure',

//     // Sidebar
//     controlPanel: 'Control panel',
//     sidebarMain: 'Main',
//     sidebarSystem: 'System',
//     sidebarLogout: 'Logout',

//     // Sidebar nav items
//     navDashboard: 'Dashboard',
//     navAnalytics: 'Analytics',
//     navProducts: 'Products',
//     navCategories: 'Categories',
//     navProductOptions: 'Product options',
//     navOrders: 'Orders',
//     navUsers: 'Users',
//     navWelcomeBonus: 'Welcome bonus',
//     navFreeProducts: 'Free products by tier',
//     navAddonRules: 'Add-on Rules',
//     navSettings: 'Settings',

//     // Header
//     headerToggleLight: 'Switch to light mode',
//     headerToggleDark: 'Switch to dark mode',

//     // Dashboard
//     dashboardTitle: 'Dashboard',
//     dashboardSubtitle: 'Welcome! Here\'s an overview of your business.',
//     ordersToday: 'Orders today',
//     ordersPlacedToday: 'orders placed today',
//     revenueToday: 'Revenue today',
//     totalEarnings: 'total earnings',
//     newUsers: 'New users',
//     registrationsToday: 'registrations today',
//     revenueThisMonth: 'Revenue this month',
//     salesLast7Days: 'Sales last 7 days',
//     ordersByStatus: 'Orders by status',
//     recentOrders: 'Recent orders',
//     last10Orders: 'Last 10 orders placed',
//     viewAll: 'View all',
//     noRecentOrders: 'No recent orders',
//     couldNotLoadData: 'Could not load data',
//     couldNotLoadDashboard: 'Could not load dashboard data',
//     product: 'product',
//     products: 'products',
//     revenue: 'Revenue',
//     client: 'Client',

//     // Order statuses
//     statusPending: 'Pending',
//     statusConfirmed: 'Confirmed',
//     statusPreparing: 'Preparing',
//     statusDelivering: 'Delivering',
//     statusDelivered: 'Delivered',
//     statusCancelled: 'Cancelled',

//     // Orders page
//     ordersTitle: 'Orders',
//     ordersSubtitle: 'View and manage orders',
//     orderId: 'Order ID',
//     date: 'Date',
//     type: 'Type',
//     inLocation: 'In-location',
//     delivery: 'Delivery',
//     addressLocation: 'Address / Location',
//     total: 'Total',
//     payment: 'Payment',
//     status: 'Status',
//     card: 'Card',
//     cash: 'Cash',
//     newOrderAlert: '🔔 New order!',
//     newOrdersCount: '{count} new {orderWord} pending',
//     newOrderSingular: 'order',
//     newOrderPlural: 'orders',
//     viewOrders: 'View orders',
//     allOrders: 'All orders',
//     filterByStatus: 'Filter by status',
//     fulfillmentType: 'Fulfillment type',
//     all: 'All',
//     selected: 'selected',
//     changeStatus: 'Change status:',
//     bulkUpdate: 'Bulk update',
//     updated: 'updated',
//     errors: 'errors',
//     searchOrderPlaceholder: 'Search by ID or address...',
//     noOrders: 'No orders',
//     orderDetails: 'Order details',
//     placedOn: 'Placed on',
//     clientInfo: 'Client information',
//     tel: 'Tel:',
//     deliveryAddress: 'Delivery address',
//     inLocationLabel: 'In-location',
//     inLocationDesc: 'Order picked up in-location. Deliver order to table indicated by client.',
//     tableLabel: 'Table to deliver to:',
//     tableNotSet: '— (client did not specify table)',
//     tablePrefix: 'Table',
//     tableCorrection: 'Correct table number:',
//     tableOptional: '(optional, if client made a mistake)',
//     tableUpdated: 'Table number updated',
//     couldNotUpdateTable: 'Could not update table number',
//     productsLabel: 'Products',
//     subtotal: 'Subtotal',
//     deliveryLabel: 'Delivery',
//     freeProducts: 'Free products',
//     currentStatus: 'Current status:',
//     paymentMethod: 'Payment method:',
//     statusUpdated: 'Status updated to "{status}"',
//     statusUpdateError: 'Error updating status',

//     // Products page
//     productsTitle: 'Products',
//     productsSubtitle: 'Manage menu products',
//     addProduct: 'Add product',
//     category: 'Category',
//     allCategories: 'All categories',
//     image: 'Image',
//     name: 'Name',
//     price: 'Price',
//     rating: 'Rating',
//     available: 'Available',
//     unavailable: 'Unavailable',
//     recommended: 'Recommended',
//     yes: 'Yes',
//     no: 'No',
//     editProduct: 'Edit product',
//     addNewProduct: 'Add new product',
//     productFormSubtitle: 'Fill in the product details',
//     productImage: 'Product image',
//     imageUploadHint: 'Click to upload an image.\nMax 5MB, JPG, PNG or WebP format',
//     imageTooLarge: 'Image must be less than 5MB',
//     nameRequired: 'Name is required',
//     priceRequired: 'Price must be a valid number',
//     categoryRequired: 'Select a category',
//     priceLabel: 'Price ({currency}) *',
//     categoryLabel: 'Category *',
//     prepTimeLabel: 'Preparation time (minutes)',
//     ingredientsLabel: 'Ingredients',
//     ingredientsPlaceholder: 'Flour, mozzarella, tomatoes, basil...',
//     ingredientsSeparator: 'Separate ingredients with commas',
//     allergensLabel: 'Allergens (optional)',
//     allergensPlaceholder: 'Gluten, dairy, eggs...',
//     allergensSeparator: 'Separate allergens with commas (e.g.: gluten, dairy)',
//     availableForOrders: 'Available for orders',
//     recommendedLabel: 'Recommended (appears in "Recommended for you")',
//     recommendedDesc: 'Marked products appear on the main page in the Recommended section',
//     displayOrder: 'Display order (optional)',
//     displayOrderDesc: 'Lower number = displayed first. Leave empty = last.',
//     addonToCart: 'Cart add-on',
//     addonActiveDesc: 'Appears in the "Add to order" section on the Cart page',
//     addonDisabledDesc: 'Add-ons plugin is disabled in Settings → Plugins',
//     productUpdated: 'Product updated successfully',
//     productCreated: 'Product created successfully',
//     productSaveError: 'Error saving product',
//     confirmDeleteProduct: 'Confirm deletion',
//     confirmDeleteProductDesc: 'Are you sure you want to delete the product "{name}"? This action cannot be undone.',
//     productDeleted: 'Product deleted successfully',
//     productDeleteError: 'Error deleting product',
//     searchProducts: 'Search products...',
//     noProducts: 'No products',
//     descriptionLabel: 'Description',
//     descriptionPlaceholder: 'Product description...',
//     selectPlaceholder: 'Select...',

//     // Categories page
//     categoriesTitle: 'Categories',
//     categoriesSubtitle: 'Manage product categories',
//     addCategory: 'Add category',
//     noCategoriesEmpty: 'No categories. Add the first category to get started.',
//     editCategory: 'Edit category',
//     addNewCategory: 'Add new category',
//     categoryFormSubtitle: 'Fill in the category details',
//     slugLabel: 'Identifier (slug) *',
//     slugDesc: 'Used internally for identification (no spaces, lowercase only)',
//     slugError: 'Identifier can only contain lowercase letters, numbers and underscores',
//     displayNameLabel: 'Display name *',
//     displayNameRequired: 'Display name is required',
//     identifierRequired: 'Identifier is required',
//     descriptionCatLabel: 'Description',
//     descriptionCatPlaceholder: 'Category description...',
//     categoryIcon: 'Category icon',
//     selectIconHint: 'Select an icon for this category',
//     categoryUpdated: 'Category updated successfully',
//     categoryCreated: 'Category created successfully',
//     categorySaveError: 'Error saving category',
//     confirmDeleteCategory: 'Confirm deletion',
//     confirmDeleteCategoryDesc: 'Are you sure you want to delete the category "{name}"?',
//     categoryWarningProducts: 'Warning: This category contains {count} products!',
//     categoryDeleted: 'Category deleted successfully',
//     categoryDeleteError: 'Error deleting category',

//     // Users page
//     usersTitle: 'Users',
//     usersSubtitle: 'Manage users and permissions',
//     user: 'User',
//     orders: 'Orders',
//     role: 'Role',
//     registered: 'Registered',
//     admin: 'Admin',
//     moderator: 'Moderator',
//     userRole: 'User',
//     blocked: 'Blocked',
//     active: 'Active',
//     makeAdmin: 'Make admin',
//     makeModerator: 'Make moderator',
//     makeUser: 'Make user',
//     block: 'Block',
//     unblock: 'Unblock',
//     blockUser: 'Block user',
//     unblockUser: 'Unblock user',
//     blockConfirmDesc: 'Are you sure you want to block the user "{name}"? They will no longer be able to access their account.',
//     unblockConfirmDesc: 'Are you sure you want to unblock the user "{name}"?',
//     userBlocked: 'User blocked successfully',
//     userUnblocked: 'User unblocked successfully',
//     userBlockError: 'Error blocking user',
//     roleUpdated: 'Role updated to "{role}"',
//     roleUpdateError: 'Error updating role',
//     userDetails: 'User details',
//     totalOrders: 'Total orders',
//     searchUsersPlaceholder: 'Search by name or email...',
//     noUsers: 'No users',
//     csvHeaders: {
//       id: 'ID',
//       name: 'Name',
//       role: 'Role',
//       status: 'Status',
//       orders: 'Orders',
//       points: 'Points',
//       registered: 'Registered',
//     },

//     // Settings page
//     settingsTitle: 'Settings',
//     settingsSubtitle: 'Configure application options',
//     saveChanges: 'Save changes',
//     settingsSaved: 'Settings saved',
//     settingsSavedDesc: 'Changes have been applied successfully.',
//     settingsLoadError: 'Could not load settings.',
//     settingsSaveError: 'Could not save settings.',
//     deliveryAndOrders: 'Delivery and in-location orders',
//     deliveryAndOrdersDesc: 'Configure fees, delivery conditions and options for in-location orders',
//     deliveryFeeLabel: 'Delivery fee ({currency})',
//     minOrderLabel: 'Minimum order ({currency})',
//     freeDeliveryLabel: 'Free delivery from ({currency})',
//     hasTables: 'Location has tables',
//     hasTablesDesc: 'If enabled, the table number field is shown in admin for in-location orders. Disable for bakeries or shops without tables.',
//     operatingHours: 'Operating hours',
//     operatingHoursDesc: 'Set opening and closing hours',
//     openingTime: 'Opening time',
//     closingTime: 'Closing time',
//     contactInfo: 'Contact information',
//     contactInfoDesc: 'Contact details displayed in the app',
//     contactEmail: 'Contact email',
//     contactPhone: 'Contact phone',
//     pointsPerOrder: 'Points per delivered order',
//     pointsPerOrderDesc: 'Shop rule: how many points are awarded for each order marked as "delivered" (fixed value, before tier multipliers).',
//     pointsPerOrderLabel: 'Points per order',
//     pointsPerOrderHint: 'Example: 5 or 7. Without the points system enabled in Plugins, this value has no effect.',
//     plugins: 'Plugins',
//     pluginsDesc: 'Enable or disable additional modules',
//     pluginLoyaltyPoints: 'Loyalty points',
//     pluginLoyaltyPointsDesc: 'Allows users to earn and use points for discounts at checkout',
//     pluginStreakCampaigns: 'Streak campaigns',
//     pluginStreakDesc: 'Streak-type campaigns (consecutive days, days per week, working days) with bonus points',
//     pluginWelcomeBonus: 'Welcome bonus points',
//     pluginWelcomeBonusDesc: 'Popup and allocation on registration. The number of points is set on the "Welcome bonus" page in the menu.',
//     pluginAddons: 'Cart add-ons',
//     pluginAddonsDesc: 'The "Add to order" section in cart – sauces, drinks, dessert, sides; future: per-product rules',
//     pluginTiers: 'Tiers plugin',
//     pluginTiersDesc: 'XP-based level-up system with points multiplier per tier. Detailed settings are on the Tiers page.',
//     pluginFreeProducts: 'Free products by tier',
//     pluginFreeProductsDesc: 'Allows defining campaigns with free products for specific tiers within a limited time period.',

//     // Welcome bonus
//     welcomeBonusTitle: 'Welcome bonus',
//     welcomeBonusSubtitle: 'How many points a new user receives on registration (popup + account credit).',
//     giftPoints: 'Gift points',
//     giftPointsDesc: 'The value is only used if both Loyalty Points and Welcome Bonus plugins are enabled in Settings. 0 = no points and no popup.',
//     pointsCount: 'Points amount',
//     pointsExample: 'Example: 5, 10 or 25.',
//     welcomeBonusSaved: 'Welcome bonus points updated.',
//     welcomeBonusLoadError: 'Could not load settings.',
//     welcomeBonusSaveError: 'Could not save.',

//     // Analytics
//     analyticsErrorMsg: 'This chart or table could not be displayed. Try reloading the page or switching tabs.',
//     analyticsLoadError: 'Could not load analytics',

//     // Product options
//     productOptionsTitle: 'Product options',
//     productOptionsSubtitle: 'Define option templates per category and apply them to products',
//     categorySelect: 'Category:',
//     chooseCategory: 'Choose a category',
//     newTemplate: 'New template',
//     noTemplates: 'No option templates for {category}',
//     noTemplatesHint: 'Create a template to define common options (e.g.: Size, Extra topping)',
//     createTemplate: 'Create template',
//     templateNameRequired: 'Template name is required',
//     groupNameRequired: 'Each group must have a name',
//     groupNeedsOption: 'Group "{name}" needs at least one option',
//     templateUpdated: 'Template updated',
//     templateCreated: 'Template created',
//     templateSaveError: 'Error saving',
//     templateDeleted: 'Template deleted (products keep their local options)',
//     templateDeleteError: 'Error deleting',
//     templateApplied: 'Template applied to {count} product(s)',
//     templateApplyError: 'Error applying',
//     templateSynced: 'Synced',
//     templateSyncResult: '{count} product(s) updated',
//     templateSyncError: 'Error syncing',
//     groups: 'group(s)',
//     synced: 'synced',

//     // Streak admin
//     recurrenceConsecutive: 'Consecutive days (Classic streak)',
//     recurrenceRolling: 'Rolling window',
//     rewardSingle: 'Single threshold (All or Nothing)',
//     rewardSteps: 'Incremental thresholds (Ladder)',
//     rewardMultiplier: 'Streak multiplier',
//     imageSaved: 'Image saved',
//     imagesSaveError: 'Could not save image',
//     couldNotLoadEnrollments: 'Could not load enrollments',
//     datesRequired: 'Start and end dates are required',
//     daysMinimum: 'Number of days must be >= 1',
//     datesOrder: 'Start date must be before end date',

//     // Points admin
//     couldNotLoadThresholds: 'Could not load points thresholds',
//     invalidThresholdData: 'Invalid data',
//     invalidThresholdDesc: 'Points and discount must be positive numbers.',
//     thresholdDeleted: 'Threshold deleted',
//     couldNotDeleteThreshold: 'Could not delete',

//     // Tiers admin
//     tiersLoadError: 'Could not load tier settings.',
//     tiersSaved: 'Settings saved',
//     tiersSavedDesc: 'Tier settings have been updated.',
//     tiersSaveError: 'Could not save settings.',
//     tiersListLoadError: 'Could not load loyalty tiers.',
//     confirmDeleteTier: 'Are you sure you want to delete this tier?',
//     tierDeleted: 'Tier deleted',
//     tierDeleteError: 'Could not delete tier.',
//     tierSaveError: 'Could not save changes.',
//     editTier: 'Edit tier',
//     addNewTier: 'Add new tier',

//     // Addon rules
//     addonFreeDelivery: 'Free delivery',
//     addonLowPrice: 'Low price',
//     addonAddedToCart: 'Added to cart',

//     // Error boundary
//     errorOccurred: 'An error occurred',
//     errorFallbackMessage: 'Something went wrong. You can try reloading the page.',
//     reloadPage: 'Reload page',

//     // Misc
//     ordersCsvHeaders: ['ID', 'Date', 'Client', 'Email', 'Phone', 'Address', 'City', 'Type', 'Subtotal', 'Delivery', 'Total', 'Payment', 'Status'],
//   },

//   // Validation messages (extended)
//   validationExtended: {
//     passwordMinChars: 'Password must be at least 8 characters',
//     passwordUppercase: 'Password must contain at least one uppercase letter',
//     passwordLowercase: 'Password must contain at least one lowercase letter',
//     passwordDigit: 'Password must contain at least one digit',
//     confirmPassword: 'Confirm password',
//     passwordsNoMatch: 'Passwords do not match',
//     addressMin: 'Address must be at least 5 characters',
//     cityMin: 'City must be at least 2 characters',
//     labelRequired: 'Label is required',
//     acceptTerms: 'You must accept the Terms and Conditions',
//   },

//   // Checkout success
//   checkoutSuccess: {
//     orderPlaced: 'Order placed!',
//     orderStatus: 'Order status',
//     stepReceived: 'Order received',
//     stepConfirmed: 'Confirmed',
//     stepPreparing: 'Preparing',
//     stepDelivering: 'Delivering',
//     stepDelivered: 'Delivered',
//     estimatedTime: 'Estimated time:',
//     orderedProducts: 'Ordered products',
//     subtotal: 'Subtotal',
//     delivery: 'Delivery',
//     free: 'Free',
//     pointsDiscount: 'Points discount',
//     freeProducts: 'Free products',
//     total: 'Total',
//     savedAmount: '🔥 You saved {amount} {currency} on this order!',
//     pointsEarned: '+{points} points earned!',
//     totalBalance: 'Total balance:',
//     points: 'points',
//     currentLevel: 'Current level',
//     xpRemaining: '{xp} XP remaining to {tier}',
//     deliveryDetails: 'Delivery details',
//     tableService: 'Table service',
//     tablePrefixed: 'Table {number}',
//     cashPayment: 'Cash payment',
//     cardPayment: 'Card payment',
//     orderAgain: 'Order again',
//     orderAgainPoints: 'Order again — earn more points!',
//     viewAllOrders: 'View all orders',
//     myOrders: 'My orders',
//     confirmingPayment: 'Confirming payment...',
//     paymentConfirmError: 'Error confirming payment',
//     paymentFailed: 'Payment confirmation failed',
//     backToCheckout: 'Back to checkout',
//     redirecting: 'Redirecting to login...',
//     requestNewLink: 'Request new link',
//     backToLogin: 'Back to login',
//   },

//   // Catalog extended
//   catalogExtended: {
//     productFound: '{count} product found',
//     productsFound: '{count} products found',
//     inCategory: ' in category "{category}"',
//     forSearch: ' for "{query}"',
//   },

//   // Cart progress texts
//   cartProgress: {
//     freeDelivery: 'Free delivery',
//     addMoreFreeDelivery: 'Add {amount} {currency} more — free delivery',
//     freeDeliveryUnlocked: '🎉 FREE delivery unlocked!',
//     addMoreFreeDeliveryGamified: 'Add {amount} {currency} for FREE delivery!',
//     freeProductUnlocked: '{product} free unlocked',
//     addMoreFreeProduct: 'Add {amount} {currency} more — {product} free',
//     freeProductsUnlockedGamified: '🎁 FREE products unlocked: {products}!',
//     addMoreFreeProductGamified: 'Add {amount} {currency} and get {product} FREE!',
//     checkoutSavings: 'Checkout — save {amount} {currency}',
//     product: 'Product',
//   },

//   // Tier display texts
//   tierDisplay: {
//     beginner: 'Beginner',
//     pointsMultiplierBenefit: 'Get x{mult} points on every delivered order',
//     orderForXp: 'Order to earn XP and advance',
//     nextTierPoints: 'x{mult} points on every order',
//     xpPerRon: '+1 XP for every {amount} {currency} spent',
//     xpPerOrder: 'XP accumulates with every order',
//   },

//   // Category display names
//   categoryNames: {
//     pizza: 'Pizza',
//     burger: 'Burgers',
//     paste: 'Pasta',
//     salate: 'Salads',
//     desert: 'Desserts',
//     bauturi: 'Drinks',
//   },

//   // Footer
//   footer: {
//     termsAndConditions: 'Terms & Conditions',
//     phone: '0800 123 456',
//     email: 'contact@foodorder.com',
//     location: 'New York, USA',
//     hours: [
//       'Mon - Fri: 10:00 - 23:00',
//       'Saturday: 11:00 - 00:00',
//       'Sunday: 11:00 - 22:00',
//     ],
//   },

//   // Streak campaign card texts
//   streakCard: {
//     consecutiveDays: 'Consecutive days',
//     rollingWindow: 'Rolling window',
//     streakBroken: 'Streak broken 😞',
//     notEnoughDays: 'Not enough days remaining 😔',
//     canLeaveAndJoin: 'You can leave this campaign and join another.',
//     rewardThresholds: 'Reward thresholds',
//     earnBonusPoints: 'Earn BONUS points',
//     activeCampaigns: 'Active Campaigns',
//     completeStreakExclusive: 'Complete the streak and unlock exclusive rewards',
//     completeStreakBonus: 'Complete the streak and earn bonus points',
//   },

//   // Product configurator / modal
//   modal: {
//     processing: 'Processing...',
//   },
// } as const;

// export type TextsType = typeof texts;


export const texts = {
    // Informații aplicație
    app: {
      name: 'FoodOrder',
      tagline: 'Comandă mâncare delicioasă, livrată rapid',
      copyright: '© 2024 FoodOrder. Toate drepturile rezervate.',
    },
  
    // Navigare
    nav: {
      home: 'Acasă',
      catalog: 'Catalog',
      cart: 'Coș',
      profile: 'Profil',
      login: 'Autentificare',
      signup: 'Înregistrare',
      logout: 'Deconectare',
      coupons: 'Cupoane',
      streakCampaigns: 'Campanii',
    },
  
    // Pagina principală
    home: {
      heroTitle: 'Mâncare delicioasă la ușa ta',
      categories: 'Categorii',
      recommended: 'Recomandate pentru tine',
      totalProductsInMenu: '{count} produse în meniu',
      viewAll: 'Vezi toate',
      /** Poartă inițială pe Home (logo + intrare); la refresh se arată din nou. */
      enterStore: 'Intră în magazin',
      orderNow: 'Comandă acum',
      heroOrderNowBadge: 'Comandă acum!',
      heroWelcomeBack: 'Bine ai revenit, {name}!',
      heroPointsLabel: '{count} puncte',
      heroPointsAvailable: 'disponibile de cheltuit',
      heroEarnPoints: 'Câștigă puncte cu fiecare comandă',
      heroEarnPointsDesc: 'Fiecare comandă îți aduce puncte de loialitate pe care le poți folosi pentru reduceri la comenzile viitoare.',
      heroMyRank: 'Rangul meu',
      heroMyPoints: 'Punctele mele',
      heroBenefits: 'Beneficii',
      heroHowItWorks: 'Cum funcționează',
      heroHowPointsWork: 'Comandă → Câștigă puncte → Folosește-le pentru reduceri',
      heroHowRanksWork: 'Comenzi → XP → rang mai mare → mai multe recompense',
      heroSignUpCta: 'Înregistrează-te pentru recompense',
      heroGuestFomo: 'Alți clienți câștigă deja puncte bonus!',
      heroGuestFomoReward: 'Nu rata recompensele.',
      heroGuestFreeProductsHint:
        'Rangurile superioare deblochează produse gratuite. Înregistrează-te și comandă pentru a avansa.',
      welcomeTitle: 'Câștigă puncte la fiecare comandă',
      welcomeStepOrderTitle: 'Comandă și câștigă puncte',
      welcomeStepRanksTitle: 'Deblochează recompense pe rang',
      welcomeStepAdvanceTitle: 'Avansează în rang',
      welcomeRegisterNow: 'Register now',
      /** Coloana primary pe Welcome (desktop): previzualizare produse */
      welcomeProductPeekTitle: 'Din meniu',
      welcomeProductPeekHint: 'Apasă pentru detalii',
      /** Bandă urgență / gamificare sub conținutul Welcome (timer decorativ) */
      welcomeUrgencyKicker: 'Timp limitat',
      welcomeUrgencyEndsIn: 'Se încheie în',
      welcomeUrgencyGamifyLines: [
        'Puncte bonus pentru comenzile plasate în această fereastră.',
        'Runda se apropie de final — nu amâna înregistrarea.',
        'Comandă acum și urcă mai rapid în rang.',
        'Zeci de clienți au activat deja bonusul de loialitate.',
        'Ultima șansă în această rundă de recompense.',
        'Fiecare minut contează pentru XP și beneficii.',
      ],
      heroXpProgress: '{current} / {target} XP',
      heroXpRemaining: 'mai ai {count} XP',
      heroMaxLevel: 'Nivel maxim atins!',
      heroNextRank: 'Următor:',
      heroUnlocks: 'Deblochează:',
      heroOrderForXp: 'Comandă acum!',
      heroFreeProductsSeeAbove: 'Recompensele tale gratuite active sunt afișate în cardul de mai sus.',
      heroNoFreeProducts: 'Campanii speciale cu produse gratuite pot apărea oricând.',
      heroFreeCampaignUrgencyKicker: 'Timp limitat',
      /** Banner urgență: „Oferta pentru {category} expiră în ” + timp (categorii separate prin virgulă dacă sunt mai multe). */
      heroFreeCampaignOfferExpiresWithCategory: 'Oferta pentru {category} expiră în ',
      /** Dacă nu putem determina categoria din campanii. */
      heroFreeCampaignOfferExpiresFallback: 'Oferta expiră în ',
      /** @deprecated folosit în alte layout-uri; păstrat pentru compatibilitate */
      heroFreeCampaignAfterTime:
        'Produsul gratis nu va dura la nesfârșit, câștigă-l acum!',
    },
  
    // Pagini autentificare
    auth: {
      loginTitle: 'Bine ai revenit!',
      loginSubtitle: 'Autentifică-te pentru a continua',
      signupTitle: 'Creează cont',
      signupSubtitle: 'Înregistrează-te pentru a plasa comenzi',
      emailLabel: 'Email',
      emailPlaceholder: 'exemplu@email.com',
      passwordLabel: 'Parolă',
      passwordPlaceholder: 'Introduceți parola',
      confirmPasswordLabel: 'Confirmă parola',
      confirmPasswordPlaceholder: 'Reintroduceți parola',
      nameLabel: 'Nume complet',
      namePlaceholder: 'Ion Popescu',
      phoneLabel: 'Telefon',
      phonePlaceholder: '+40 700 000 000',
      loginButton: 'Autentifică-te',
      signupButton: 'Creează cont',
      forgotPassword: 'Ai uitat parola?',
      forgotPasswordTitle: 'Resetează parola',
      forgotPasswordSubtitle: 'Introduceți emailul contului și vă vom trimite un link de resetare.',
      forgotPasswordButton: 'Trimite link de resetare',
      forgotPasswordSuccess: 'Dacă există un cont cu acest email, vei primi un link de resetare a parolei.',
      resetPasswordTitle: 'Parolă nouă',
      resetPasswordSubtitle: 'Introduceți noua parolă pentru contul dumneavoastră.',
      resetPasswordButton: 'Resetează parola',
      resetPasswordSuccess: 'Parola a fost resetată. Te poți autentifica acum cu noua parolă.',
      resetPasswordInvalidToken: 'Link-ul de resetare este invalid sau a expirat. Te rugăm să soliciți unul nou.',
      noAccount: 'Nu ai cont?',
      hasAccount: 'Ai deja cont?',
      orContinueWith: 'sau continuă cu',
    },
  
    // Pagina profil
    profile: {
      title: 'Profilul meu',
      editProfile: 'Editează profilul',
      saveChanges: 'Salvează',
      cancel: 'Anulează',
      orderHistory: 'Istoricul comenzilor',
      noOrders: 'Nu ai nicio comandă încă.',
      personalInfo: 'Informații personale',
      addressLabel: 'Adresă',
      addressPlaceholder: 'Stradă, număr, bloc, apartament',
      cityLabel: 'Oraș',
      cityPlaceholder: 'București',
      settings: 'Setările contului',
      deliveryAddresses: 'Adrese de livrare',
      noAddresses: 'Nicio adresă salvată',
      addAddress: 'Adaugă adresă',
      editAddress: 'Editează adresa',
      deleteAddress: 'Șterge adresa',
      setAsDefault: 'Setează ca implicită',
      defaultAddress: 'Adresă implicită',
      addressLabelField: 'Etichetă',
      addressLabelPlaceholder: 'ex.: Acasă, Birou',
      resetPassword: 'Resetează parola',
      resetPasswordDesc: 'Trimite un email pentru resetarea parolei',
      resetPasswordButton: 'Trimite email de resetare',
      resetPasswordSent: 'Emailul de resetare a fost trimis',
      deleteAccount: 'Șterge contul',
      deleteAccountDesc: 'Această acțiune este ireversibilă',
      deleteAccountButton: 'Șterge contul permanent',
      deleteAccountConfirmText: 'ȘTERGE CONTUL',
      deleteAccountWarning: 'Pentru a confirma ștergerea, introduceți parola și scrieți "ȘTERGE CONTUL"',
      accountDeleted: 'Contul a fost șters',
    },
  
    // Pagina catalog
    catalog: {
      title: 'Catalog',
      allCategories: 'Toate categoriile',
      filterBy: 'Filtrează după',
      sortBy: 'Sortează după',
      priceAsc: 'Preț: mic spre mare',
      priceDesc: 'Preț: mare spre mic',
      nameAsc: 'Nume A-Z',
      noProducts: 'Niciun produs găsit.',
      addToCart: 'Adaugă în coș',
      added: 'Adăugat!',
    },
  
    // Pagina detalii produs
    productDetails: {
      ingredients: 'Ingrediente',
      allergens: 'Alergeni',
      reviews: 'Recenzii',
      noReviews: 'Nicio recenzie încă.',
      similarProducts: 'Produse similare',
      preparationTime: 'Timp de preparare',
      minutes: 'min',
      backToCatalog: 'Înapoi la catalog',
      addToCart: 'Adaugă în coș',
      outOfStock: 'Stoc epuizat',
    },
  
    // Pagina coș
    cart: {
      title: 'Coșul tău',
      empty: 'Coșul tău este gol',
      emptySubtitle: 'Adaugă produse pentru a continua',
      continueShopping: 'Continuă cumpărăturile',
      subtotal: 'Subtotal',
      delivery: 'Livrare',
      total: 'Total',
      checkout: 'Finalizează comanda',
      remove: 'Elimină',
      quantity: 'Cantitate',
      freeDelivery: 'Livrare gratuită',
      deliveryCost: 'Cost livrare',
    },
  
    // Pagina finalizare comandă
    checkout: {
      title: 'Finalizare comandă',
      deliveryInfo: 'Informații livrare',
      paymentMethod: 'Metodă de plată',
      cash: 'Numerar la livrare',
      card: 'Card credit / debit',
      orderSummary: 'Sumar comandă',
      placeOrder: 'Plasează comanda',
      processing: 'Se procesează...',
      orderSuccess: 'Comanda a fost plasată cu succes!',
      orderSuccessMessage: 'Vei primi un email de confirmare în scurt timp.',
      backToHome: 'Înapoi acasă',
      backToSavedAddresses: 'Alege o adresă salvată',
      activeCouponsTitle: 'Cupoane active',
      noEligibleCouponsForCart: 'Nu ai cupoane active aplicabile produselor din coșul curent.',
      couponForProduct: 'la {product}',
      pointsDisabledByCoupons: 'Punctele de loialitate nu pot fi folosite împreună cu cupoane aplicate pe comandă.',
    },

    coupons: {
      pageTitle: 'Cupoane',
      homeCardTitle: 'Activeaza cupoane',
      homeCardSubtitle: 'Activează cupoane din puncte și folosește reduceri la checkout.',
      homeCardAvailableCount: '{count} Active',
      homeCardCta: 'Activează →',
      emptyCatalog: 'Nu există cupoane disponibile.',
      loginRequiredTitle: 'Autentificare necesară',
      loginRequiredDescription: 'Conectează-te pentru a activa cupoane.',
      activateSuccessTitle: 'Cupon activat',
      activateSuccessDescription: 'Cuponul a fost adăugat în portofel.',
      activateErrorDescription: 'Nu s-a putut activa cuponul.',
      defaultDescription: 'Reducere la produs țintă',
      discountLabel: 'Reducere:',
      forProduct: 'la {product}',
      costLabel: 'Cost: {points} puncte',
      missingPoints: 'Îți lipsesc {points} puncte',
      requiredTier: 'Necesită rangul {tier}',
      superiorTierFallback: 'superior',
      alreadyActive: 'Cupon deja activ în portofel',
      alreadyActivatedButton: 'Deja activat',
      activateButton: 'Activează cuponul',
    },

    myCoupons: {
      pageTitle: 'Cupoanele mele',
      empty: 'Nu ai cupoane activate încă.',
      discountLabel: 'Reducere:',
      forProduct: 'la {product}',
      statusLabel: 'Status:',
      statusActive: 'Activ',
      statusUsed: 'Folosit',
      statusExpired: 'Expirat',
      activatedAtLabel: 'Activat la:',
      usedAtLabel: 'Folosit la:',
      expiresAtLabel: 'Expiră la:',
      usedHint: 'Pentru o nouă comandă, activează din nou cuponul din pagina Cupoane.',
    },
  
    // Mesaje validare
    validation: {
      required: 'Acest câmp este obligatoriu',
      invalidEmail: 'Email invalid',
      passwordMin: 'Parola trebuie să aibă cel puțin 6 caractere',
      passwordMatch: 'Parolele nu coincid',
      invalidPhone: 'Număr de telefon invalid',
      invalidName: 'Numele trebuie să aibă cel puțin 2 caractere',
    },
  
    // Notificări
    notifications: {
      loginSuccess: 'Autentificat cu succes!',
      loginError: 'Email sau parolă incorectă',
      signupSuccess: 'Cont creat cu succes!',
      signupError: 'Eroare la crearea contului',
      logoutSuccess: 'Deconectat',
      profileUpdated: 'Profil actualizat',
      addedToCart: 'Produs adăugat în coș',
      removedFromCart: 'Produs eliminat din coș',
      orderPlaced: 'Comanda a fost plasată cu succes!',
      orderError: 'Eroare la plasarea comenzii',
      networkError: 'Eroare de rețea. Te rugăm să încerci din nou.',
      addressSaved: 'Adresa a fost salvată',
      addressDeleted: 'Adresa a fost ștearsă',
      passwordResetError: 'Eroare la trimiterea emailului',
      deleteAccountError: 'Eroare la ștergerea contului',
      invalidPassword: 'Parolă incorectă',
      invalidConfirmText: 'Textul de confirmare nu este corect',
    },
  
    // Comun
    common: {
      loading: 'Se încarcă...',
      error: 'A apărut o eroare',
      retry: 'Încearcă din nou',
      close: 'Închide',
      confirm: 'Confirmă',
      currency: 'RON',
      back: 'Înapoi',
    },
  
    // Bonus de bun venit la prima autentificare
    welcomeBonus: {
      title: 'Ai câștigat {count} puncte!',
      description: 'Le poți folosi la următoarea comandă pentru o reducere.',
      goToProducts: 'Mergi la produse',
    },
  
    // Analytics Admin
    analytics: {
      title: 'Analiză',
      subtitle: 'Rapoarte avansate despre afacerea ta',
      grossRevenue: 'Venit brut total',
      netProfitPerOrder: 'Profit net per comandă',
      aov: 'Valoare medie comandă (VMC)',
      salesByCategory: 'Volum vânzări pe categorie',
      revenueGrowthRate: 'Rata de creștere a veniturilor',
      totalDeliveryFees: 'Total taxe de livrare colectate',
      totalOrders: 'Total comenzi',
      vsPreviousPeriod: 'față de perioada anterioară',
      noData: 'Nu există date disponibile',
      topCustomers: 'Cei mai fideli clienți',
      frequentlyOrderedTogether: 'Comandate frecvent împreună',
      fulfillmentDeliveryVsInLocation: 'Livrare vs. La locație',
      fulfillmentTrend: 'Tendință fulfillment pe săptămână',
      delivery: 'Livrare',
      inLocation: 'La locație',
      revenue: 'Venit',
      orders: 'comenzi',
      cancellationRate: 'Rată de anulare',
      cancelledOrders: 'comenzi anulate',
      peakHours: 'Ore de vârf',
      dailyRevenueTrend: 'Tendință venit zilnic',
      pointsTitle: 'Analiză puncte de loialitate',
      pointsEarned: 'Puncte câștigate',
      pointsSpent: 'Puncte cheltuite',
      redemptionRate: 'Rată de utilizare puncte',
      redemptions: 'Utilizări',
      uniqueEarners: 'Utilizatori unici (câștigare)',
      uniqueRedeemers: 'Utilizatori unici (utilizare)',
      aovWithPoints: 'VMC cu puncte',
      aovWithoutPoints: 'VMC fără puncte',
      totalDiscountFromPoints: 'Total reduceri din puncte',
      topPointsEarners: 'Top câștigători de puncte',
      pointsTrend: 'Tendință zilnică puncte',
      balance: 'Sold',
      earned: 'Câștigate',
      spent: 'Cheltuite',
      streaksTitle: 'Analiză campanii streak',
      enrolled: 'Înscriși',
      completed: 'Finalizate',
      active: 'Active',
      avgStreak: 'Streak mediu',
      pointsAwarded: 'Puncte acordate',
      completionRate: 'Rată de finalizare',
      tiersTitle: 'Analiză ranguri',
      tierName: 'Nivel',
      userCount: 'Utilizatori',
      tierRevenue: 'Venit pe rang',
      tierAvgOrder: 'Comandă medie',
      tierMultiplier: 'Multiplicator',
      tierDistribution: 'Distribuție utilizatori pe rang',
      tierLtv: 'Valoare per rang',
    },
  
    // Plugin produse gratuite
    freeProducts: {
      adminTitle: 'Campanii produse gratuite pe rang',
      adminSubtitle:
        'Configurați campanii în care anumite produse devin gratuite pentru clienții dintr-un rang specific, într-o perioadă limitată.',
      adminMenuLabel: 'Produse gratuite pe rang',
      listTitle: 'Campanii',
      listDescription:
        'Fiecare campanie se aplică unui singur rang. Puteți crea mai multe campanii pentru ranguri sau perioade diferite.',
      listEmpty:
        'Nicio campanie. Creați una nouă pentru a oferi produse gratuite clienților fideli.',
      loading: 'Se încarcă...',
      createButton: 'Campanie nouă',
      editDialogTitle: 'Editează campania de produse gratuite',
      createDialogTitle: 'Campanie nouă de produse gratuite',
      dialogSubtitle:
        'Alegeți rangul țintă, perioada și produsele care vor fi gratuite pentru clienți.',
      nameLabel: 'Numele campaniei',
      namePlaceholder: 'ex.: Cafea gratuită pentru membrii Gold',
      tierLabel: 'Rang',
      tierPlaceholder: 'Alege rang',
      customTextLabel: 'Mesaj afișat clientului (opțional)',
      customTextPlaceholder: 'ex.: Produs gratuit pentru rangul tău de loialitate',
      startDateLabel: 'Data de început',
      endDateLabel: 'Data de sfârșit',
      minOrderValueLabel: 'Valoare minimă comandă (RON)',
      minOrderValueHelp: '0 = fără minim. Produsul gratuit se aplică doar peste acest prag.',
      productsLabel: 'Produse gratuite în campanie',
      productsHelp:
        'Bifați produsele care vor fi gratuite pentru utilizatorii din rangul selectat (max. 1 unitate per produs per comandă).',
      productsEmpty: 'Niciun produs în catalog.',
      productsCount: '{count} produse',
      activeBadge: 'Activ',
      cancel: 'Anulează',
      save: 'Salvează',
      deleteTitle: 'Șterge campania?',
      deleteDescription: 'Campania "{name}" va fi ștearsă permanent.',
      deleteConfirm: 'Șterge',
      toastLoadError: 'Nu s-au putut încărca campaniile sau datele auxiliare',
      toastSaveError: 'Eroare la salvare',
      toastDeleteError: 'Eroare la ștergere',
      toastCreated: 'Campanie creată',
      toastUpdated: 'Campanie actualizată',
      toastDeleted: 'Campanie ștearsă',
      validationNameRequired: 'Numele este obligatoriu',
      validationTierRequired: 'Te rugăm să selectezi un rang',
      validationDatesRequired: 'Data de început și de sfârșit sunt obligatorii',
      validationDatesOrder: 'Data de început trebuie să fie înainte de data de sfârșit',
      validationMinOrderValue:
        'Valoarea minimă a comenzii trebuie să fie un număr mai mare sau egal cu 0',
      warnNoProducts:
        'Campania nu are produse selectate. Poți continua, dar nu va avea efect până nu adaugi produse.',
      rankInfoNone:
        'Nu ai momentan produse gratuite pentru rangul tău, dar campanii speciale pot apărea oricând.',
      rankInfoActivePrefix: 'Ai produse gratuite active pentru rangul tău:',
      rankInfoMinOrder:
        'Comandă cel puțin {amount} RON în coș și primești 1 unitate din fiecare produs din categoriile de mai jos gratuit.',
      rankInfoNoMinOrder:
        'Adaugă un produs din categoriile de mai jos în coș și îl primești gratuit (1 unitate).',
      rankInfoCta: 'Adaugă în coș pentru a beneficia.',
      availableOnlyForYourRank: 'Produse gratuite doar pentru rangul tău!',
      cartGridTitle: 'Produse gratuite pentru rangul tău',
      cartDiscountLabel: 'Produse gratuite',
      cartInfoNone:
        'Uneori poți primi produse gratuite pentru rangul tău de loialitate — urmărește ofertele speciale.',
    },
  
    // Streak V2 marketing
    streak: {
      pageTitle: 'Campanii Streak',
      pageSubtitle: 'Completează provocările și câștigă puncte bonus',
      noCampaigns: 'Nicio campanie activă în acest moment.',
      homeCardTitle: 'Câștigă puncte BONUS',
      homeCardActive: 'Streak activ — menține streak-ul!',
      homeCardAvailable: 'Provocări disponibile — înscrie-te acum!',
      homeCardLost: 'Ai pierdut un streak — vezi detalii!',
      homeCardCompleted: 'Streak finalizat — felicitări! 🎉',
      homeCardCta: 'Vezi provocările',
      homeCardPoints: '+{points} puncte posibile',
      comboCardTitle: 'Combouri speciale',
      comboCardSubtitle: 'În curând...',
      homeGamifiedDealUnit: 'puncte bonus',
      homeGamifiedUrgencyDays: '{days} zile rămase',
      homeGamifiedUrgencyTwo: 'Ultimele 2 zile',
      homeGamifiedUrgencyLast: 'Ultima zi — nu rata bonusul',
      homeGamifiedTrustAvailable: 'Exclusiv pentru provocări — bonus mai mare decât o comandă obișnuită.',
      homeGamifiedHeadlineAvailable: 'Cea mai bună ofertă de puncte',
      homeGamifiedHeadlineActive: 'Bonus mare la finalul provocării',
      homeGamifiedSubActive: 'Mai ai nevoie de comenzi — nu întrerupe streak-ul.',
      homeGamifiedHeadlineLost: 'Poți începe o nouă provocare',
      homeGamifiedHeadlineCompleted: 'Ai deblocat bonusul',
      homeGamifiedSubCompleted: 'Felicitări — punctele sunt ale tale.',
      homeGamifiedCtaAvailable: 'Înscrie-te și câștigă',
      homeGamifiedCtaActive: 'Continuă provocarea',
      homeGamifiedCtaLost: 'Vezi provocările',
      homeGamifiedCtaCompleted: 'Descoperă alte oferte',
      preview: {
        earnPrefix: 'Castiga',
        pointsSuffix: 'puncte',
        ordersLabel: 'Comenzi',
        thresholdOrderLabel: 'comandă',
        statusLive: 'Live',
        statusUrgent: 'Urgent',
        statusLastChance: 'Last chance',
        statusFailed: 'Lost',
        statusCompleted: 'Completed',
        ctaJoin: 'Join',
        ctaActive: 'Active',
        ctaCompleted: 'Done',
        ctaDetails: 'Activeaza',
        ctaUnlock: 'Deblocheaza',
        lostOverlay: 'Pierdut',
        lossShort: 'Do not lose your progress!',
        daysLeft: '{days} days!',
        leave: 'Leave',
      },
      detail: {
        title: 'Campaign details',
        subtitle: 'Full rules, rewards, progress, and actions',
      },
    },
  
    // Texte admin comune
    admin: {
      error: 'Eroare',
      success: 'Succes',
      save: 'Salvează',
      saving: 'Se salvează...',
      cancel: 'Anulează',
      delete: 'Șterge',
      deleting: 'Se șterge...',
      edit: 'Editează',
      add: 'Adaugă',
      create: 'Creează',
      search: 'Caută...',
      noData: 'Nu există date de afișat',
      rowsPerPage: 'Rânduri pe pagină:',
      processing: 'Se procesează...',
      loading: 'Se încarcă...',
      view: 'Vezi',
      disconnect: 'Deconectează',
      export: 'Exportă CSV',
      loginTitle: 'Food Admin',
      loginSubtitle: 'Autentifică-te pentru a accesa panoul de administrare',
      loginEmailLabel: 'Email',
      loginPasswordLabel: 'Parolă',
      loginButton: 'Autentifică-te',
      loginAuthenticating: 'Se autentifică...',
      loginSuccess: 'Autentificare reușită',
      loginFailed: 'Autentificare eșuată',
      loginDevCredentials: 'Credențiale implicite: admin@foodorder.com / admin123secure',
      controlPanel: 'Panou de control',
      sidebarMain: 'Principal',
      sidebarSystem: 'Sistem',
      sidebarLogout: 'Deconectare',
      navDashboard: 'Tablou de bord',
      navAnalytics: 'Analiză',
      navProducts: 'Produse',
      navCategories: 'Categorii',
      navProductOptions: 'Opțiuni produse',
      navOrders: 'Comenzi',
      navUsers: 'Utilizatori',
      navWelcomeBonus: 'Bonus de bun venit',
      navFreeProducts: 'Produse gratuite pe rang',
      navAddonRules: 'Reguli suplimente',
      navSettings: 'Setări',
      headerToggleLight: 'Comută la modul luminos',
      headerToggleDark: 'Comută la modul întunecat',
      dashboardTitle: 'Tablou de bord',
      dashboardSubtitle: 'Bun venit! Iată o prezentare generală a afacerii tale.',
      ordersToday: 'Comenzi azi',
      ordersPlacedToday: 'comenzi plasate azi',
      revenueToday: 'Venit azi',
      totalEarnings: 'câștiguri totale',
      newUsers: 'Utilizatori noi',
      registrationsToday: 'înregistrări azi',
      revenueThisMonth: 'Venit luna aceasta',
      salesLast7Days: 'Vânzări ultimele 7 zile',
      ordersByStatus: 'Comenzi pe status',
      recentOrders: 'Comenzi recente',
      last10Orders: 'Ultimele 10 comenzi plasate',
      viewAll: 'Vezi toate',
      noRecentOrders: 'Nicio comandă recentă',
      couldNotLoadData: 'Nu s-au putut încărca datele',
      couldNotLoadDashboard: 'Nu s-au putut încărca datele tabloului de bord',
      product: 'produs',
      products: 'produse',
      revenue: 'Venit',
      client: 'Client',
      statusPending: 'În așteptare',
      statusConfirmed: 'Confirmată',
      statusPreparing: 'În preparare',
      statusDelivering: 'În livrare',
      statusDelivered: 'Livrată',
      statusCancelled: 'Anulată',
      ordersTitle: 'Comenzi',
      ordersSubtitle: 'Vizualizează și gestionează comenzile',
      orderId: 'ID Comandă',
      date: 'Dată',
      type: 'Tip',
      inLocation: 'La locație',
      delivery: 'Livrare',
      addressLocation: 'Adresă / Locație',
      total: 'Total',
      payment: 'Plată',
      status: 'Status',
      card: 'Card',
      cash: 'Numerar',
      newOrderAlert: '🔔 Comandă nouă!',
      newOrdersCount: '{count} {orderWord} noi în așteptare',
      newOrderSingular: 'comandă',
      newOrderPlural: 'comenzi',
      viewOrders: 'Vezi comenzile',
      allOrders: 'Toate comenzile',
      filterByStatus: 'Filtrează după status',
      fulfillmentType: 'Tip fulfillment',
      all: 'Toate',
      selected: 'selectate',
      changeStatus: 'Schimbă statusul:',
      bulkUpdate: 'Actualizare în masă',
      updated: 'actualizate',
      errors: 'erori',
      searchOrderPlaceholder: 'Caută după ID sau adresă...',
      noOrders: 'Nicio comandă',
      orderDetails: 'Detalii comandă',
      placedOn: 'Plasată pe',
      clientInfo: 'Informații client',
      tel: 'Tel:',
      deliveryAddress: 'Adresă de livrare',
      inLocationLabel: 'La locație',
      inLocationDesc: 'Comanda se ridică la locație. Livrați comanda la masa indicată de client.',
      tableLabel: 'Masa la care se livrează:',
      tableNotSet: '— (clientul nu a specificat masa)',
      tablePrefix: 'Masa',
      tableCorrection: 'Numărul corect al mesei:',
      tableOptional: '(opțional, dacă clientul a greșit)',
      tableUpdated: 'Numărul mesei actualizat',
      couldNotUpdateTable: 'Nu s-a putut actualiza numărul mesei',
      productsLabel: 'Produse',
      subtotal: 'Subtotal',
      deliveryLabel: 'Livrare',
      freeProducts: 'Produse gratuite',
      currentStatus: 'Status curent:',
      paymentMethod: 'Metodă de plată:',
      statusUpdated: 'Status actualizat la "{status}"',
      statusUpdateError: 'Eroare la actualizarea statusului',
      productsTitle: 'Produse',
      productsSubtitle: 'Gestionează produsele din meniu',
      addProduct: 'Adaugă produs',
      category: 'Categorie',
      allCategories: 'Toate categoriile',
      image: 'Imagine',
      name: 'Nume',
      price: 'Preț',
      rating: 'Rating',
      available: 'Disponibil',
      unavailable: 'Indisponibil',
      recommended: 'Recomandat',
      yes: 'Da',
      no: 'Nu',
      editProduct: 'Editează produsul',
      addNewProduct: 'Adaugă produs nou',
      productFormSubtitle: 'Completați detaliile produsului',
      productImage: 'Imaginea produsului',
      imageUploadHint: 'Click pentru a încărca o imagine.\nMax 5MB, format JPG, PNG sau WebP',
      imageTooLarge: 'Imaginea trebuie să fie mai mică de 5MB',
      nameRequired: 'Numele este obligatoriu',
      priceRequired: 'Prețul trebuie să fie un număr valid',
      categoryRequired: 'Selectați o categorie',
      priceLabel: 'Preț ({currency}) *',
      categoryLabel: 'Categorie *',
      prepTimeLabel: 'Timp de preparare (minute)',
      ingredientsLabel: 'Ingrediente',
      ingredientsPlaceholder: 'Făină, mozzarella, roșii, busuioc...',
      ingredientsSeparator: 'Separați ingredientele cu virgulă',
      allergensLabel: 'Alergeni (opțional)',
      allergensPlaceholder: 'Gluten, lactate, ouă...',
      allergensSeparator: 'Separați alergenii cu virgulă (ex.: gluten, lactate)',
      availableForOrders: 'Disponibil pentru comenzi',
      recommendedLabel: 'Recomandat (apare în "Recomandate pentru tine")',
      recommendedDesc: 'Produsele marcate apar pe pagina principală în secțiunea Recomandate',
      displayOrder: 'Ordine de afișare (opțional)',
      displayOrderDesc: 'Număr mai mic = afișat primul. Lasă gol = ultimul.',
      addonToCart: 'Supliment coș',
      addonActiveDesc: 'Apare în secțiunea "Adaugă la comandă" pe pagina Coș',
      addonDisabledDesc: 'Plugin-ul suplimente este dezactivat în Setări → Plugin-uri',
      productUpdated: 'Produs actualizat cu succes',
      productCreated: 'Produs creat cu succes',
      productSaveError: 'Eroare la salvarea produsului',
      confirmDeleteProduct: 'Confirmă ștergerea',
      confirmDeleteProductDesc: 'Ești sigur că vrei să ștergi produsul "{name}"? Această acțiune nu poate fi anulată.',
      productDeleted: 'Produs șters cu succes',
      productDeleteError: 'Eroare la ștergerea produsului',
      searchProducts: 'Caută produse...',
      noProducts: 'Niciun produs',
      descriptionLabel: 'Descriere',
      descriptionPlaceholder: 'Descrierea produsului...',
      selectPlaceholder: 'Selectează...',
      categoriesTitle: 'Categorii',
      categoriesSubtitle: 'Gestionează categoriile de produse',
      addCategory: 'Adaugă categorie',
      noCategoriesEmpty: 'Nicio categorie. Adaugă prima categorie pentru a începe.',
      editCategory: 'Editează categoria',
      addNewCategory: 'Adaugă categorie nouă',
      categoryFormSubtitle: 'Completați detaliile categoriei',
      slugLabel: 'Identificator (slug) *',
      slugDesc: 'Folosit intern pentru identificare (fără spații, doar litere mici)',
      slugError: 'Identificatorul poate conține doar litere mici, cifre și underscore',
      displayNameLabel: 'Nume afișat *',
      displayNameRequired: 'Numele afișat este obligatoriu',
      identifierRequired: 'Identificatorul este obligatoriu',
      descriptionCatLabel: 'Descriere',
      descriptionCatPlaceholder: 'Descrierea categoriei...',
      categoryIcon: 'Iconița categoriei',
      selectIconHint: 'Selectați o icooniță pentru această categorie',
      categoryUpdated: 'Categorie actualizată cu succes',
      categoryCreated: 'Categorie creată cu succes',
      categorySaveError: 'Eroare la salvarea categoriei',
      confirmDeleteCategory: 'Confirmă ștergerea',
      confirmDeleteCategoryDesc: 'Ești sigur că vrei să ștergi categoria "{name}"?',
      categoryWarningProducts: 'Atenție: Această categorie conține {count} produse!',
      categoryDeleted: 'Categorie ștearsă cu succes',
      categoryDeleteError: 'Eroare la ștergerea categoriei',
      usersTitle: 'Utilizatori',
      usersSubtitle: 'Gestionează utilizatorii și permisiunile',
      user: 'Utilizator',
      orders: 'Comenzi',
      role: 'Rol',
      registered: 'Înregistrat',
      admin: 'Administrator',
      moderator: 'Moderator',
      userRole: 'Utilizator',
      blocked: 'Blocat',
      active: 'Activ',
      makeAdmin: 'Fă administrator',
      makeModerator: 'Fă moderator',
      makeUser: 'Fă utilizator',
      block: 'Blochează',
      unblock: 'Deblochează',
      blockUser: 'Blochează utilizatorul',
      unblockUser: 'Deblochează utilizatorul',
      blockConfirmDesc: 'Ești sigur că vrei să blochezi utilizatorul "{name}"? Nu va mai putea accesa contul.',
      unblockConfirmDesc: 'Ești sigur că vrei să deblochezi utilizatorul "{name}"?',
      userBlocked: 'Utilizator blocat cu succes',
      userUnblocked: 'Utilizator deblocat cu succes',
      userBlockError: 'Eroare la blocarea utilizatorului',
      roleUpdated: 'Rol actualizat la "{role}"',
      roleUpdateError: 'Eroare la actualizarea rolului',
      userDetails: 'Detalii utilizator',
      totalOrders: 'Total comenzi',
      searchUsersPlaceholder: 'Caută după nume sau email...',
      noUsers: 'Niciun utilizator',
      csvHeaders: {
        id: 'ID',
        name: 'Nume',
        role: 'Rol',
        status: 'Status',
        orders: 'Comenzi',
        points: 'Puncte',
        registered: 'Înregistrat',
      },
      settingsTitle: 'Setări',
      settingsSubtitle: 'Configurează opțiunile aplicației',
      saveChanges: 'Salvează modificările',
      settingsSaved: 'Setări salvate',
      settingsSavedDesc: 'Modificările au fost aplicate cu succes.',
      settingsLoadError: 'Nu s-au putut încărca setările.',
      settingsSaveError: 'Nu s-au putut salva setările.',
      deliveryAndOrders: 'Livrare și comenzi la locație',
      deliveryAndOrdersDesc: 'Configurați taxele, condițiile de livrare și opțiunile pentru comenzile la locație',
      deliveryFeeLabel: 'Taxă de livrare ({currency})',
      minOrderLabel: 'Comandă minimă ({currency})',
      freeDeliveryLabel: 'Livrare gratuită de la ({currency})',
      hasTables: 'Locația are mese',
      hasTablesDesc: 'Dacă este activat, câmpul pentru numărul mesei apare în admin pentru comenzile la locație. Dezactivați pentru brutării sau magazine fără mese.',
      operatingHours: 'Program de funcționare',
      operatingHoursDesc: 'Setați orele de deschidere și închidere',
      openingTime: 'Ora de deschidere',
      closingTime: 'Ora de închidere',
      contactInfo: 'Informații de contact',
      contactInfoDesc: 'Datele de contact afișate în aplicație',
      contactEmail: 'Email contact',
      contactPhone: 'Telefon contact',
      pointsPerOrder: 'Puncte per comandă livrată',
      pointsPerOrderDesc: 'Regula magazinului: câte puncte se acordă pentru fiecare comandă marcată ca "livrată" (valoare fixă, înainte de multiplicatorii de rang).',
      pointsPerOrderLabel: 'Puncte per comandă',
      pointsPerOrderHint: 'Exemplu: 5 sau 7. Fără sistemul de puncte activat în Plugin-uri, această valoare nu are efect.',
      plugins: 'Plugin-uri',
      pluginsDesc: 'Activează sau dezactivează module suplimentare',
      pluginLoyaltyPoints: 'Puncte de loialitate',
      pluginLoyaltyPointsDesc: 'Permite utilizatorilor să câștige și să folosească puncte pentru reduceri la finalizarea comenzii',
      pluginStreakCampaigns: 'Campanii streak',
      pluginStreakDesc: 'Campanii de tip streak (zile consecutive, zile pe săptămână, zile lucrătoare) cu puncte bonus',
      pluginWelcomeBonus: 'Puncte bonus de bun venit',
      pluginWelcomeBonusDesc: 'Popup și alocare la înregistrare. Numărul de puncte se setează pe pagina "Bonus de bun venit" din meniu.',
      pluginAddons: 'Suplimente coș',
      pluginAddonsDesc: 'Secțiunea "Adaugă la comandă" în coș – sosuri, băuturi, desert, garnituri',
      pluginTiers: 'Plugin ranguri',
      pluginTiersDesc: 'Sistem de avansare bazat pe XP cu multiplicator de puncte per rang. Setările detaliate sunt pe pagina Ranguri.',
      pluginFreeProducts: 'Produse gratuite pe rang',
      pluginFreeProductsDesc: 'Permite definirea de campanii cu produse gratuite pentru ranguri specifice într-o perioadă limitată.',
      welcomeBonusTitle: 'Bonus de bun venit',
      welcomeBonusSubtitle: 'Câte puncte primește un utilizator nou la înregistrare (popup + credit în cont).',
      giftPoints: 'Puncte cadou',
      giftPointsDesc: 'Valoarea este folosită doar dacă atât plugin-ul Puncte de Loialitate cât și plugin-ul Bonus de Bun Venit sunt activate în Setări. 0 = fără puncte și fără popup.',
      pointsCount: 'Număr de puncte',
      pointsExample: 'Exemplu: 5, 10 sau 25.',
      welcomeBonusSaved: 'Punctele de bun venit au fost actualizate.',
      welcomeBonusLoadError: 'Nu s-au putut încărca setările.',
      welcomeBonusSaveError: 'Nu s-a putut salva.',
      analyticsErrorMsg: 'Acest grafic sau tabel nu a putut fi afișat. Încearcă să reîncarci pagina sau să schimbi tab-ul.',
      analyticsLoadError: 'Nu s-au putut încărca datele de analiză',
      productOptionsTitle: 'Opțiuni produse',
      productOptionsSubtitle: 'Definește șabloane de opțiuni per categorie și aplică-le produselor',
      categorySelect: 'Categorie:',
      chooseCategory: 'Alege o categorie',
      newTemplate: 'Șablon nou',
      noTemplates: 'Niciun șablon de opțiuni pentru {category}',
      noTemplatesHint: 'Creați un șablon pentru a defini opțiuni comune (ex.: Mărime, Topping extra)',
      createTemplate: 'Creează șablon',
      templateNameRequired: 'Numele șablonului este obligatoriu',
      groupNameRequired: 'Fiecare grup trebuie să aibă un nume',
      groupNeedsOption: 'Grupul "{name}" necesită cel puțin o opțiune',
      templateUpdated: 'Șablon actualizat',
      templateCreated: 'Șablon creat',
      templateSaveError: 'Eroare la salvare',
      templateDeleted: 'Șablon șters (produsele păstrează opțiunile lor locale)',
      templateDeleteError: 'Eroare la ștergere',
      templateApplied: 'Șablon aplicat la {count} produs(e)',
      templateApplyError: 'Eroare la aplicare',
      templateSynced: 'Sincronizat',
      templateSyncResult: '{count} produs(e) actualizat(e)',
      templateSyncError: 'Eroare la sincronizare',
      groups: 'grup(uri)',
      synced: 'sincronizat',
      recurrenceConsecutive: 'Zile consecutive (Streak clasic)',
      recurrenceRolling: 'Fereastră glisantă',
      rewardSingle: 'Prag unic (Totul sau Nimic)',
      rewardSteps: 'Praguri incrementale (Scară)',
      rewardMultiplier: 'Multiplicator streak',
      imageSaved: 'Imagine salvată',
      imagesSaveError: 'Nu s-a putut salva imaginea',
      couldNotLoadEnrollments: 'Nu s-au putut încărca înscrierile',
      datesRequired: 'Datele de început și de sfârșit sunt obligatorii',
      daysMinimum: 'Numărul de zile trebuie să fie >= 1',
      datesOrder: 'Data de început trebuie să fie înainte de data de sfârșit',
      couldNotLoadThresholds: 'Nu s-au putut încărca pragurile de puncte',
      invalidThresholdData: 'Date invalide',
      invalidThresholdDesc: 'Punctele și reducerea trebuie să fie numere pozitive.',
      thresholdDeleted: 'Prag șters',
      couldNotDeleteThreshold: 'Nu s-a putut șterge',
      tiersLoadError: 'Nu s-au putut încărca setările de rang.',
      tiersSaved: 'Setări salvate',
      tiersSavedDesc: 'Setările de rang au fost actualizate.',
      tiersSaveError: 'Nu s-au putut salva setările.',
      tiersListLoadError: 'Nu s-au putut încărca rangurile de loialitate.',
      confirmDeleteTier: 'Ești sigur că vrei să ștergi acest rang?',
      tierDeleted: 'Rang șters',
      tierDeleteError: 'Nu s-a putut șterge rangul.',
      tierSaveError: 'Nu s-au putut salva modificările.',
      editTier: 'Editează rangul',
      addNewTier: 'Adaugă rang nou',
      addonFreeDelivery: 'Livrare gratuită',
      addonLowPrice: 'Preț redus',
      addonAddedToCart: 'Adăugat în coș',
      errorOccurred: 'A apărut o eroare',
      errorFallbackMessage: 'Ceva nu a funcționat. Poți încerca să reîncarci pagina.',
      reloadPage: 'Reîncarcă pagina',
      ordersCsvHeaders: ['ID', 'Dată', 'Client', 'Email', 'Telefon', 'Adresă', 'Oraș', 'Tip', 'Subtotal', 'Livrare', 'Total', 'Plată', 'Status'],
    },

    adminCoupons: {
      pageTitle: 'Admin cupoane',
      createCardTitle: 'Creează cupon',
      titleLabel: 'Titlu',
      targetProductLabel: 'Produs țintă',
      targetProductPlaceholder: 'Alege produsul',
      discountLabel: 'Reducere %',
      pointsCostLabel: 'Cost puncte',
      requiredTierLabel: 'Rang minim necesar',
      requiredTierPlaceholder: 'Alege rang minim',
      noTierRequired: 'Fără rang minim',
      imageLabel: 'Imagine cupon',
      imageUploading: 'Se încarcă imaginea...',
      imageUploaded: 'Imagine încărcată',
      imageUploadErrorTitle: 'Eroare upload',
      imageUploadError: 'Nu s-a putut încărca imaginea',
      imagePreviewAlt: 'Previzualizare cupon',
      descriptionLabel: 'Descriere',
      activeLabel: 'Activ',
      analyticsTitle: 'Analitice cupoane',
      totalDiscountLabel: 'Reducere totală acordată',
      totalActivatedLabel: 'Activate',
      totalUsedLabel: 'Folosite',
      usageRateLabel: 'Rata utilizare',
      listTitle: 'Lista cupoane',
      deactivate: 'Dezactivează',
      activate: 'Activează',
      created: 'Cupon creat',
      createError: 'Nu s-a putut crea cuponul',
      loadError: 'Nu s-au putut încărca cupoanele',
      missingProductTitle: 'Produs lipsă',
      missingProductDescription: 'Selectează produsul țintă pentru cupon.',
      pointsLabel: 'puncte',
      targetShort: 'target',
    },
  
    // Mesaje validare extinse
    validationExtended: {
      passwordMinChars: 'Parola trebuie să aibă cel puțin 8 caractere',
      passwordUppercase: 'Parola trebuie să conțină cel puțin o literă mare',
      passwordLowercase: 'Parola trebuie să conțină cel puțin o literă mică',
      passwordDigit: 'Parola trebuie să conțină cel puțin o cifră',
      confirmPassword: 'Confirmă parola',
      passwordsNoMatch: 'Parolele nu coincid',
      addressMin: 'Adresa trebuie să aibă cel puțin 5 caractere',
      cityMin: 'Orașul trebuie să aibă cel puțin 2 caractere',
      labelRequired: 'Eticheta este obligatorie',
      acceptTerms: 'Trebuie să accepți Termenii și Condițiile',
    },
  
    // Succes finalizare comandă
    checkoutSuccess: {
      orderPlaced: 'Comandă plasată!',
      orderStatus: 'Status comandă',
      stepReceived: 'Comandă primită',
      stepConfirmed: 'Confirmată',
      stepPreparing: 'În preparare',
      stepDelivering: 'În livrare',
      stepDelivered: 'Livrată',
      estimatedTime: 'Timp estimat:',
      orderedProducts: 'Produse comandate',
      subtotal: 'Subtotal',
      delivery: 'Livrare',
      free: 'Gratuit',
      pointsDiscount: 'Reducere din puncte',
      freeProducts: 'Produse gratuite',
      total: 'Total',
      savedAmount: '🔥 Ai economisit {amount} {currency} la această comandă!',
      pointsEarned: '+{points} puncte câștigate!',
      totalBalance: 'Sold total:',
      points: 'puncte',
      currentLevel: 'Nivel curent',
      xpRemaining: 'mai ai {xp} XP până la {tier}',
      deliveryDetails: 'Detalii livrare',
      tableService: 'Servire la masă',
      tablePrefixed: 'Masa {number}',
      cashPayment: 'Plată cu numerar',
      cardPayment: 'Plată cu cardul',
      orderAgain: 'Comandă din nou',
      orderAgainPoints: 'Comandă din nou — câștigă mai multe puncte!',
      viewAllOrders: 'Vezi toate comenzile',
      myOrders: 'Comenzile mele',
      confirmingPayment: 'Se confirmă plata...',
      paymentConfirmError: 'Eroare la confirmarea plății',
      paymentFailed: 'Confirmarea plății a eșuat',
      backToCheckout: 'Înapoi la finalizare comandă',
      redirecting: 'Redirecționare către autentificare...',
      requestNewLink: 'Solicită link nou',
      backToLogin: 'Înapoi la autentificare',
    },
  
    // Catalog extins
    catalogExtended: {
      productFound: '{count} produs găsit',
      productsFound: '{count} produse găsite',
      inCategory: ' în categoria "{category}"',
      forSearch: ' pentru "{query}"',
    },
  
    // Texte progres coș
    cartProgress: {
      freeDelivery: 'Livrare gratuită',
      addMoreFreeDelivery: 'Adaugă {amount} {currency} — livrare gratuită',
      freeDeliveryUnlocked: '🎉 Livrare GRATUITĂ deblocată!',
      addMoreFreeDeliveryGamified: 'Adaugă {amount} {currency} pentru livrare GRATUITĂ!',
      freeProductUnlocked: '{product} gratuit deblocat',
      addMoreFreeProduct: 'Adaugă {amount} {currency} — {product} gratuit',
      freeProductsUnlockedGamified: '🎁 Produse GRATUITE deblocate: {products}!',
      addMoreFreeProductGamified: 'Adaugă {amount} {currency} și primești {product} GRATUIT!',
      checkoutSavings: 'Finalizează — economisești {amount} {currency}',
      product: 'Produs',
    },
  
    // Texte afișare rang
    tierDisplay: {
      beginner: 'Începător',
      pointsMultiplierBenefit: 'Primești x{mult} puncte la fiecare comandă livrată',
      orderForXp: 'Comandă pentru a câștiga XP și a avansa',
      nextTierPoints: 'x{mult} puncte la fiecare comandă',
      xpPerRon: '+1 XP pentru fiecare {amount} {currency} cheltuiți',
      xpPerOrder: 'XP se acumulează cu fiecare comandă',
    },
  
    // Nume categorii
    categoryNames: {
      pizza: 'Pizza',
      burger: 'Burgeri',
      paste: 'Paste',
      salate: 'Salate',
      desert: 'Deserturi',
      bauturi: 'Băuturi',
    },
  
    // Footer
    footer: {
      termsAndConditions: 'Termeni și Condiții',
      phone: '0800 123 456',
      email: 'contact@foodorder.com',
      location: 'București, România',
      hours: [
        'Lun - Vin: 10:00 - 23:00',
        'Sâmbătă: 11:00 - 00:00',
        'Duminică: 11:00 - 22:00',
      ],
    },
  
    // Texte card campanie streak
    streakCard: {
      consecutiveDays: 'Zile consecutive',
      rollingWindow: 'Fereastră glisantă',
      streakBroken: 'Streak întrerupt 😞',
      notEnoughDays: 'Nu mai sunt suficiente zile 😔',
      canLeaveAndJoin: 'Poți părăsi această campanie și te poți înscrie în alta.',
      rewardThresholds: 'Praguri de recompensă',
      earnBonusPoints: 'Câștigă puncte BONUS',
      activeCampaigns: 'Campanii active',
      completeStreakExclusive: 'Completează streak-ul și deblochează recompense exclusive',
      completeStreakBonus: 'Completează streak-ul și câștigă puncte bonus',
    },
  
    // Configurator produs / modal
    modal: {
      processing: 'Se procesează...',
    },
  } as const;
  
  export type TextsType = typeof texts;